Tinkering

diff --git a/stow/.local/bin/audio-volume b/stow/.local/bin/audio-volume
--- a/stow/.local/bin/audio-volume
+++ b/stow/.local/bin/audio-volume
@@ -1,17 +1,62 @@
 #!/usr/bin/env bash
 
-# Set the audio volume and show a notification.
-
 set -eu
 
-action=${1:?Missing action}
+sink=@DEFAULT_SINK@
+increment=5
+
+me=${0##*/}
+usage="Set the audio volume and show a notification.
+
+Usage:
+    $me ACTION
+
+Options:
+    -i NUMBER    increment or decrement by NUMBER percent
+                 (default: $increment)
+
+    -s NAME      change volume for NAME sink
+                 (default: $sink)
+
+Actions:
+    up           increase volume by increment
+    down         decrease volume by increment
+    mute         toggle volume mute status
+    max          set volume to maximum
+    NUMBER       set volume to NUMBER percent
+"
+
+usage() {
+    printf "%s\n" "$usage"
+    exit 0
+}
+
+die() {
+    printf "ERROR: %s\n" "$*" >&2
+    exit 1
+}
+
+while getopts ":i:s:h" option; do
+    case $option in
+    i) increment=$OPTARG ;;
+    s) sink=$OPTARG ;;
+    h) usage ;;
+    *) die "Invalid option '$OPTARG'" ;;
+    esac
+done && shift $((OPTIND - 1))
+
+if [[ ! -v 1 ]]; then
+    die "Missing action"
+fi
+
+action=$1
 
 # The following lock file guard along with the sleep command defined at the end
 # of the script will limit how often the volume can be changed, and
 # consequently, how often swaystatus will be poked. Sending the refresh signal
 # too frequently seemed to be crashing it.
 
-lock_file=$XDG_RUNTIME_DIR/${0##*/}.lock
+lock_file=$XDG_RUNTIME_DIR/$me.lock
 
 if [[ -e $lock_file ]]; then
     exit 0
@@ -20,13 +65,10 @@ fi
 touch "$lock_file"
 trap 'rm "$lock_file"' INT TERM EXIT
 
-sink=@DEFAULT_SINK@
-increment=5%
-
 case $action in
 mute) pactl set-sink-mute "$sink" toggle ;;
-up) pactl set-sink-volume "$sink" +"$increment" ;;
-down) pactl set-sink-volume "$sink" -"$increment" ;;
+up) pactl set-sink-volume "$sink" +"$increment%" ;;
+down) pactl set-sink-volume "$sink" -"$increment%" ;;
 max) pactl set-sink-volume "$sink" 100% ;;
 [0-9]*) pactl set-sink-volume "$sink" "$action" ;;
 esac
@@ -50,8 +92,9 @@ else
     icon="audio-volume-high"
 fi
 
-notify-send -u low -i "$icon" -h int:value:"$volume" \
-    -h string:x-canonical-private-synchronous:"${0##*/}" \
+notify-send -u low -i "$icon" \
+    -h int:value:"$volume" \
+    -h string:x-canonical-private-synchronous:"$me" \
     "Volume Control" "Volume: $volume"
 
 sleep 0.1
diff --git a/stow/.local/bin/brightness b/stow/.local/bin/brightness
--- a/stow/.local/bin/brightness
+++ b/stow/.local/bin/brightness
@@ -1,10 +1,43 @@
 #!/usr/bin/env bash
 
-# Set the display brightness and show a notification.
-
 set -eu
 
-action=${1:?Missing action}
+me=${0##*/}
+usage="Set the display brightness and show a notification.
+
+Usage:
+    $me ACTION
+
+Actions:
+    up        increase brightness by one step
+    down      decrease brightness by one step
+    max       set brightness to maximum
+    min       set brightness to minimum
+    NUMBER    set brightness to NUMBER
+"
+
+usage() {
+    printf "%s\n" "$usage"
+    exit 0
+}
+
+die() {
+    printf "ERROR: %s\n" "$*" >&2
+    exit 1
+}
+
+while getopts ":h" option; do
+    case $option in
+    h) usage ;;
+    *) die "Invalid option '$OPTARG'" ;;
+    esac
+done && shift $((OPTIND - 1))
+
+if [[ ! -v 1 ]]; then
+    die "Missing action"
+fi
+
+action=$1
 
 case $action in
 up) brightnessctl set 1+ ;;
@@ -17,6 +50,7 @@ esac
 value=$(brightnessctl get)
 total=$(brightnessctl max)
 
-notify-send -u low -i sunny -h int:value:"$((value * 100 / total))" \
-    -h string:x-canonical-private-synchronous:audio-volume \
+notify-send -u low -i sunny \
+    -h int:value:"$((value * 100 / total))" \
+    -h string:x-canonical-private-synchronous:"$me" \
     "Brightness" "Level: $value"
diff --git a/stow/.local/bin/capture-image-camera b/stow/.local/bin/capture-image-camera
--- a/stow/.local/bin/capture-image-camera
+++ b/stow/.local/bin/capture-image-camera
@@ -9,10 +9,11 @@ directory=$HOME
 file_name=camera_%FT%T%:z
 file_type=png
 
+me=${0##*/}
 usage="Capture an image from a video device.
 
 Usage:
-    ${0##*/} [OPTIONS] [FILE]
+    $me [OPTIONS] [FILE]
 
 Options:
     -e              edit the captured image before saving
@@ -35,6 +36,16 @@ Arguments:
                     (default: $directory/$file_name.$file_type)
 "
 
+usage() {
+    printf "%s\n" "$usage"
+    exit 0
+}
+
+die() {
+    printf "ERROR: %s\n" "$*" >&2
+    exit 1
+}
+
 while getopts ":ed:D:N:E:h" option; do
     case $option in
     e) edit=1 ;;
@@ -42,14 +53,8 @@ while getopts ":ed:D:N:E:h" option; do
     D) directory=$OPTARG ;;
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
-    h)
-        printf "%s\n" "$usage"
-        exit
-        ;;
-    *)
-        printf "ERROR: Invalid option '%s'\n" "$OPTARG"
-        exit 1
-        ;;
+    h) usage ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -75,7 +80,7 @@ fi
 canberra-gtk-play -i screen-capture &
 
 notify-send -i media-record \
-    "Captured camera photo" \
-    "<u>${output_file/$HOME/\~}</u>" &
+    "Captured camera photo:" \
+    "<u>${output_file##*/}</u>" &
 
 wl-copy -n "$output_file"
diff --git a/stow/.local/bin/capture-image-desktop b/stow/.local/bin/capture-image-desktop
--- a/stow/.local/bin/capture-image-desktop
+++ b/stow/.local/bin/capture-image-desktop
@@ -8,10 +8,11 @@ directory=$HOME
 file_name=desktop_%FT%T%:z
 file_type=png
 
+me=${0##*/}
 usage="Capture an image of the desktop.
 
 Usage:
-    ${0##*/} [OPTIONS] [FILE]
+    $me [OPTIONS] [FILE]
 
 Options:
     -g GEOMETRY     geometry of region to capture
@@ -42,6 +43,16 @@ Arguments:
                     (default: $directory/$file_name.$file_type)
 "
 
+usage() {
+    printf "%s\n" "$usage"
+    exit 0
+}
+
+die() {
+    printf "ERROR: %s\n" "$*" >&2
+    exit 1
+}
+
 geometry_format='\(.x),\(.y) \(.width)x\(.height)'
 
 focused_window_geometry() {
@@ -67,14 +78,8 @@ while getopts ":g:rfsmed:D:N:E:h" option; do
     D) directory=$OPTARG ;;
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
-    h)
-        printf "%s\n" "$usage"
-        exit
-        ;;
-    *)
-        printf "ERROR: Invalid option '%s'\n" "$OPTARG"
-        exit 1
-        ;;
+    h) usage ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -105,7 +110,7 @@ fi
 canberra-gtk-play -i screen-capture &
 
 notify-send -i media-record \
-    "Captured desktop image" \
-    "<u>${output_file/$HOME/\~}</u>" &
+    "Captured desktop image:" \
+    "<u>${output_file##*/}</u>" &
 
 wl-copy -n "$output_file"
diff --git a/stow/.local/bin/capture-pixel-desktop b/stow/.local/bin/capture-pixel-desktop
--- a/stow/.local/bin/capture-pixel-desktop
+++ b/stow/.local/bin/capture-pixel-desktop
@@ -1,11 +1,36 @@
 #!/usr/bin/env bash
 
-# Capture the color value of a selected pixel to the clipboard.
-# Usage: capture-pixel-desktop [hex|rgb|name]  # default: hex
-
 set -eu
 
-declare -A indices=([rgb]=2 [hex]=3 [name]=4)
+me=${0##*/}
+usage="Capture the color value of a selected pixel to the clipboard.
+
+Usage:
+    $me TYPE
+
+Types:
+    hex    output color as a hex string (ex: #rrggbb) (default)
+    rgb    output color as an RGB tuple (ex: (1,2,3))
+"
+
+usage() {
+    printf "%s\n" "$usage"
+    exit 0
+}
+
+die() {
+    printf "ERROR: %s\n" "$*" >&2
+    exit 1
+}
+
+while getopts ":h" option; do
+    case $option in
+    h) usage ;;
+    *) die "Invalid option '$OPTARG'" ;;
+    esac
+done && shift $((OPTIND - 1))
+
+declare -A indices=([rgb]=2 [hex]=3)
 
 name=${1:-hex}
 index=${indices[$name]}
@@ -19,7 +44,7 @@ value=$(
 canberra-gtk-play -i screen-capture &
 
 notify-send -i media-record \
-    "Captured desktop pixel" \
-    "$name: <u>$value</u>" &
+    "Captured pixel to clipboard:" \
+    "Represented as $name: <u>$value</u>" &
 
 wl-copy -n "$value"
diff --git a/stow/.local/bin/capture-video-camera b/stow/.local/bin/capture-video-camera
--- a/stow/.local/bin/capture-video-camera
+++ b/stow/.local/bin/capture-video-camera
@@ -8,11 +8,11 @@ directory=$HOME
 file_name=camera_%FT%T%:z
 file_type=mp4
 
-name=${0##*/}
+me=${0##*/}
 usage="Capture video from a camera device.
 
 Usage:
-    $name [OPTIONS] [FILE | 'stop']
+    $me [OPTIONS] [FILE | 'stop']
     
 Options:
     -a              also capture audio from microphone
@@ -40,6 +40,16 @@ Arguments:
     'stop'          stop recording session
 "
 
+usage() {
+    printf "%s\n" "$usage"
+    exit 0
+}
+
+die() {
+    printf "ERROR: %s\n" "$*" >&2
+    exit 1
+}
+
 while getopts ":ai:d:D:N:E:h" option; do
     case $option in
     a) capture_audio=1 ;;
@@ -48,18 +58,12 @@ while getopts ":ai:d:D:N:E:h" option; do
     D) directory=$OPTARG ;;
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
-    h)
-        printf "%s\n" "$usage"
-        exit
-        ;;
-    *)
-        printf "ERROR: Invalid option '%s'\n" "$OPTARG"
-        exit 1
-        ;;
+    h) usage ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
-capture_command_stdin=$XDG_RUNTIME_DIR/$name-command.stdin
+capture_command_stdin=$XDG_RUNTIME_DIR/$me-command.stdin
 
 if [[ -v 1 && $1 == stop ]]; then
     if [[ -f $capture_command_stdin ]]; then
@@ -84,12 +88,12 @@ if ((delay > 0)); then
     canberra-gtk-play -l "$delay" -i message
 fi
 
+mkdir -p "$(dirname "$output_file")"
+capture_command+=("$output_file")
+
 # If not connected to a TTY, tell ffmpeg to get its stdin from a runtime file.
 # This way, recording can be stopped remotely by writing 'q' to the file.
 # For this script, a shortcut is to give "stop" as the first argument.
-
-mkdir -p "$(dirname "$output_file")"
-capture_command+=("$output_file")
 
 if ! tty -s; then
     touch "$capture_command_stdin"
@@ -107,7 +111,7 @@ fi
 canberra-gtk-play -i screen-capture &
 
 notify-send -i media-record \
-    "Captured camera video${capture_audio:+ (with audio)}" \
-    "<u>${output_file/$HOME/\~}</u>" &
+    "Captured camera video${capture_audio:+ (with audio)}:" \
+    "<u>${output_file##*/}</u>" &
 
 wl-copy -n "$output_file"
diff --git a/stow/.local/bin/capture-video-desktop b/stow/.local/bin/capture-video-desktop
--- a/stow/.local/bin/capture-video-desktop
+++ b/stow/.local/bin/capture-video-desktop
@@ -7,11 +7,11 @@ directory=$HOME
 file_name=desktop_%FT%T%:z
 file_type=mp4
 
-name=${0##*/}
+me=${0##*/}
 usage="Capture video of the desktop.
 
 Usage:
-    $name [OPTIONS] [FILE | 'stop']
+    $me [OPTIONS] [FILE | 'stop']
     
 Options:
     -g GEOMETRY     geometry of region to capture
@@ -42,6 +42,16 @@ Arguments:
     'stop'          stop recording session
 "
 
+usage() {
+    printf "%s\n" "$usage"
+    exit 0
+}
+
+die() {
+    printf "ERROR: %s\n" "$*" >&2
+    exit 1
+}
+
 geometry_format='\(.x),\(.y) \(.width)x\(.height)'
 
 focused_window_geometry() {
@@ -66,18 +76,12 @@ while getopts ":g:rfsad:D:N:E:h" option; do
     D) directory=$OPTARG ;;
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
-    h)
-        printf "%s\n" "$usage"
-        exit
-        ;;
-    *)
-        printf "ERROR: Invalid option '%s'\n" "$OPTARG"
-        exit 1
-        ;;
+    h) usage ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
-capture_command_pid_file=$XDG_RUNTIME_DIR/$name-command.pid
+capture_command_pid_file=$XDG_RUNTIME_DIR/$me-command.pid
 
 if [[ -v 1 && $1 == stop ]]; then
     if [[ -f $capture_command_pid_file ]]; then
@@ -125,7 +129,7 @@ fi
 canberra-gtk-play -i camera-shutter &
 
 notify-send -i media-record \
-    "Captured desktop video${capture_audio:+ (with audio)}" \
-    "<u>${output_file/$HOME/\~}</u>" &
+    "Captured desktop video${capture_audio:+ (with audio)}:" \
+    "<u>${output_file##*/}</u>" &
 
 wl-copy -n "$output_file"
diff --git a/stow/.local/bin/copy-window-cwd b/stow/.local/bin/copy-window-cwd
--- a/stow/.local/bin/copy-window-cwd
+++ b/stow/.local/bin/copy-window-cwd
@@ -2,15 +2,25 @@
 
 set -eu
 
+me=${0##*/}
 usage="Copy the current working directory of a window to the clipboard.
 
 Usage:
-    ${0##*/} [OPTIONS]
+    $me [OPTIONS]
 
 Options:
-    -s    select window by clicking it
-                
-If no window is selected with -s, the current window is used."
+    -s    select a window (default: current)
+"
+
+usage() {
+    printf "%s\n" "$usage"
+    exit 0
+}
+
+die() {
+    printf "ERROR: %s\n" "$*" >&2
+    exit 1
+}
 
 select_window_id() {
     swaymsg -t get_tree |
@@ -23,14 +33,8 @@ pwd_command=(swaypwd)
 while getopts ":sh" option; do
     case $option in
     s) pwd_command+=("$(select_window_id)") ;;
-    h)
-        printf "%s\n" "$usage"
-        exit
-        ;;
-    *)
-        printf "ERROR: Invalid option '%s'\n" "$OPTARG"
-        exit 1
-        ;;
+    h) usage ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -38,6 +42,6 @@ cwd=$("${pwd_command[@]}")
 
 wl-copy -n "$cwd"
 
-notify-send -t 3000 -i edit-copy \
-    "Working directory copied to clipboard" \
-    "$cwd"
+notify-send -i edit-copy \
+    "Directory copied to clipboard:" \
+    "<u>$cwd</u>"
diff --git a/stow/.local/bin/disable-kernel-module b/stow/.local/bin/disable-kernel-module
--- a/stow/.local/bin/disable-kernel-module
+++ b/stow/.local/bin/disable-kernel-module
@@ -1,21 +1,50 @@
 #!/usr/bin/env bash
 
-# Immediately and persistently disable a kernel module.
-
 set -eu
 
-mod_name=${1:?Missing module name}
+me=${0##*/}
+usage="Immediately and persistently disable kernel modules.
 
-if ! modprobe --show --quiet "$mod_name"; then
-    printf "ERROR: Invalid module '%s'" "$mod_name" >&2
+Usage:
+    $me NAME...
+
+Arguments:
+    NAME    disable NAME module
+"
+
+usage() {
+    printf "%s\n" "$usage"
+    exit 0
+}
+
+die() {
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
+}
+
+while getopts ":h" option; do
+    case $option in
+    h) usage ;;
+    *) die "Invalid option '$OPTARG'" ;;
+    esac
+done && shift $((OPTIND - 1))
+
+if (($# == 0)); then
+    die "Missing module name(s)"
 fi
 
-# Ensure that the module is not loaded during boot.
-conf_file=/etc/modprobe.d/disable-"$mod_name".conf
-sudo tee "$conf_file" >/dev/null <<<"blacklist $mod_name"
+for name in "$@"; do
+    if ! modprobe --show --quiet "$name"; then
+        printf "ERROR: Invalid module '%s'" "$name" >&2
+        exit 1
+    fi
 
-# If the module is loaded, unload it.
-if grep -wq "^$mod_name" /proc/modules; then
-    sudo rmmod -v "$mod_name"
-fi
+    # Ensure that the module is not loaded during boot.
+    conf_file=/etc/modprobe.d/disable-"$name".conf
+    sudo tee "$conf_file" >/dev/null <<<"blacklist $name"
+
+    # If the module is loaded, unload it.
+    if grep -wq "^$name" /proc/modules; then
+        sudo rmmod -v "$name"
+    fi
+done
diff --git a/stow/.local/bin/swaymark b/stow/.local/bin/swaymark
--- a/stow/.local/bin/swaymark
+++ b/stow/.local/bin/swaymark
@@ -1,10 +1,42 @@
 #!/usr/bin/env bash
 
-# Interact with sway's container marks.
-
 set -eu
 
-action=${1:?Missing action}
+me=${0##*/}
+usage="Interact with sway's container marks.
+
+Usage: 
+    $me ACTION
+
+Actions:
+    set      set mark for current container
+    unset    remove mark for current container
+    clear    remove all container marks
+    goto     focus a marked container
+"
+
+usage() {
+    printf "%s\n" "$usage"
+    exit 0
+}
+
+die() {
+    printf "ERROR: %s\n" "$*" >&2
+    exit 1
+}
+
+while getopts ":h" option; do
+    case $option in
+    h) usage ;;
+    *) die "Invalid option '$OPTARG'" ;;
+    esac
+done && shift $((OPTIND - 1))
+
+if [[ ! -v 1 ]]; then
+    die "Missing action"
+fi
+
+action=$1
 
 case $action in
 set | goto) ;;
@@ -14,10 +46,7 @@ unset)
 clear)
     exec swaymsg unmark
     ;;
-*)
-    printf "ERROR: Invalid action '%s'\n" "$action"
-    exit 1
-    ;;
+*) die "Invalid action '$action'" ;;
 esac
 
 mark=$(
diff --git a/stow/.local/bin/swaymsg-input b/stow/.local/bin/swaymsg-input
--- a/stow/.local/bin/swaymsg-input
+++ b/stow/.local/bin/swaymsg-input
@@ -1,21 +1,52 @@
 #!/usr/bin/env bash
 
-# Prompt the user for a sway command.
-
 set -eu
 
 prompt=input
+
+me=${0##*/}
+usage="Prompt the user for sway command input.
+
+Usage:
+    $me [OPTIONS] [FORMAT]
+
+Options:
+    -p TEXT    use TEXT for input prompt 
+               (default: $prompt)
+
+    -s PATH    use sway socket PATH
+
+Arguments:
+    FORMAT     use FORMAT for sway command
+               (%s will be replaced by user input)
+"
+
+usage() {
+    printf "%s\n" "$usage"
+    exit 0
+}
+
+die() {
+    printf "ERROR: %s\n" "$*" >&2
+    exit 1
+}
+
 ipc_command=(swaymsg)
 
-while getopts "p:s:" option; do
+while getopts ":p:s:h" option; do
     case $option in
     p) prompt=$OPTARG ;;
     s) ipc_command+=(-s "$OPTARG") ;;
+    h) usage ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
-format=${1:?Missing message format}
-shift
+if [[ ! -v 1 ]]; then
+    die "Missing command format"
+fi
+
+format=$1
 
 reply=$(bemenu -p "$prompt" </dev/null)
 printf -v message "$format" "$reply"
diff --git a/stow/.local/bin/swaypwd b/stow/.local/bin/swaypwd
--- a/stow/.local/bin/swaypwd
+++ b/stow/.local/bin/swaypwd
@@ -2,26 +2,31 @@
 
 set -eu -o pipefail
 
+me=${0##*/}
 usage="Print the working directory of a window.
 
 Usage:
-    ${0##*/} [OPTIONS] [ID]
+    $me [ID]
 
-Options:
-    -h    show this help message
-                
-If no window ID is given, the current window is used."
+Arguments:
+    ID    print directory for window ID
+          (default: focused window)
+"
+
+usage() {
+    printf "%s\n" "$usage"
+    exit 0
+}
+
+die() {
+    printf "ERROR: %s\n" "$*" >&2
+    exit 1
+}
 
 while getopts ":h" option; do
     case $option in
-    h)
-        printf "%s\n" "$usage"
-        exit
-        ;;
-    *)
-        printf "ERROR: Invalid option '%s'\n" "$OPTARG"
-        exit 1
-        ;;
+    h) usage ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift "$((OPTIND - 1))"
 
@@ -37,24 +42,22 @@ else
     )
 fi
 
-cwd=$HOME # fallback
-
-if [[ -n $window_pid ]]; then
-    parent_pid=$window_pid
-
-    while child_pid=$(pgrep --parent "$parent_pid" | head -n1); do
-        parent_pid=$child_pid
-    done
-
-    pid=$parent_pid
-    cwd_link=/proc/$pid/cwd
-
-    if [[ -e $cwd_link ]]; then
-        possible_cwd=$(readlink "$cwd_link")
-        if [[ -d $possible_cwd ]]; then
-            cwd=$possible_cwd
-        fi
-    fi
+# If unable to get a window PID, provide a fallback.
+if [[ -z $window_pid ]]; then
+    printf "$HOME"
+    exit 0
 fi
 
-printf "%s" "$cwd"
+pid=$window_pid
+
+while next_pid=$(pgrep --parent "$pid" | head -n1); do
+    # Some child processes don't inherit the working directory of the
+    # parent process. If they are encountered, stop looking for children.
+    case "$(readlink /proc/"$next_pid"/exe)" in
+    */wl-copy) break ;;
+    esac
+
+    pid=$next_pid
+done
+
+readlink /proc/"$pid"/cwd
