Tinkering

diff --git a/stow/.local/bin/audio-volume b/stow/.local/bin/audio-volume
--- a/stow/.local/bin/audio-volume
+++ b/stow/.local/bin/audio-volume
@@ -9,36 +9,22 @@ action=${1:?missing action}
 increment=5
 
 case $action in
-mute)
-    pamixer --toggle-mute
-    ;;
-down)
-    pamixer --decrease $increment
-    icon=audio-volume-low
-    ;;
-up)
-    pamixer --increase $increment
-    icon=audio-volume-medium
-    ;;
-max)
-    pamixer --set-volume 100
-    icon=audio-volume-high
-    ;;
+mute) pamixer --toggle-mute ;;
+down) pamixer --decrease $increment ;;
+up) pamixer --increase $increment ;;
+max) pamixer --set-volume 100 ;;
 esac
 
-# Exit code corresponds to mute status.
-muted=$(pamixer --get-mute) || true
+# The exit code corresponds to mute status.
+muted=$(pamixer --get-mute) || true # -e will cause exit otherwise
 
 volume=$(pamixer --get-volume)
 
-if [[ $action == mute && $muted == true ]]; then
-    icon="audio-volume-muted"
-else
-    icon="audio-volume-high"
-fi
-
 canberra-gtk-play -i audio-volume-change &
 
-notify-send -u low -i "${icon:-auto-volume-high}" \
+icon="audio-volume-high"
+[[ $muted == true ]] && icon="audio-volume-muted"
+
+notify-send -u low -i "$icon" -h int:value:"$volume" \
     -h string:x-canonical-private-synchronous:audio-volume \
-    "Volume Control" "Volume: $volume%<br>Muted: $muted"
+    "Volume Control" "Muted: <b>$muted</b><br>Volume: <b>$volume%</b>"
