Tinkering

diff --git a/stow/.local/bin/capture-image-camera b/stow/.local/bin/capture-image-camera
--- a/stow/.local/bin/capture-image-camera
+++ b/stow/.local/bin/capture-image-camera
@@ -23,18 +23,21 @@ Environment Variables:
     FILE_TYPE   extension to use for output file name (default: $file_type)
 "
 
+usage() {
+    echo "$usage" >&2
+    exit 0
+}
+
+die() {
+    echo "$me: $*" >&2
+    exit 1
+}
+
 unset OPTIND OPTARG
 while getopts ":h" option; do
     case $option in
-    h)
-        echo "$usage" >&2
-        exit 0
-        ;;
-
-    *)
-        echo "invalid option '$option'" >&2
-        exit 1
-        ;;
+    h) usage ;;
+    *) die "invalid option '$option'" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/stow/.local/bin/capture-image-desktop b/stow/.local/bin/capture-image-desktop
--- a/stow/.local/bin/capture-image-desktop
+++ b/stow/.local/bin/capture-image-desktop
@@ -22,33 +22,33 @@ Environment Variables:
     FILE_TYPE    extension to use for capture file name (default: $file_type)
 "
 
+usage() {
+    echo "$usage" >&2
+    exit 0
+}
+
+die() {
+    echo "$me: $*" >&2
+    exit 1
+}
+
 unset OPTIND OPTARG
 while getopts ":huws" option; do
     case $option in
-    h)
-        echo "$usage" >&2
-        exit 0
-        ;;
-
+    h) usage ;;
     u)
         name="window"
         geometry=$(xwinrect -id "$(active-window)")
         ;;
-
     w)
         name="window"
         geometry=$(xwinrect -id "$(selected-window)")
         ;;
-
     s)
         name="region"
         geometry=$(xrectsel)
         ;;
-
-    *)
-        echo "invalid option '$option'"
-        exit 1
-        ;;
+    *) die "invalid option '$option'" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -57,7 +57,7 @@ mkdir -p "$(dirname "$file")"
 
 options=(-window root)
 
-[[ $geometry ]] && options+=(-crop "$geometry")
+[[ -n $geometry ]] && options+=(-crop "$geometry")
 
 import "${options[@]}" "$file"
 
diff --git a/stow/.local/bin/capture-video-camera b/stow/.local/bin/capture-video-camera
--- a/stow/.local/bin/capture-video-camera
+++ b/stow/.local/bin/capture-video-camera
@@ -24,18 +24,21 @@ Environment Variables:
     FILE_TYPE    extension to use for capture file name (default: $file_type)
 "
 
+usage() {
+    echo "$usage" >&2
+    exit 0
+}
+
+die() {
+    echo "$me: $*" >&2
+    exit 1
+}
+
 unset OPTIND OPTARG
 while getopts ":h" option; do
     case $option in
-    h)
-        echo "$usage" >&2
-        exit 0
-        ;;
-
-    *)
-        echo "invalid option '$option'" >&2
-        exit 1
-        ;;
+    h) usage ;;
+    *) die "invalid option '$option'" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -52,7 +55,7 @@ mkdir -p "$(dirname "$file")"
 options=(-hide_banner -loglevel error)
 options+=(-y -f v4l2 -i "$device" -f alsa -i default)
 
-[[ $DURATION ]] && options+=(-t "$DURATION")
+[[ -n $DURATION ]] && options+=(-t "$DURATION")
 
 canberra-gtk-play -l "$delay" -i message-new-instant
 
diff --git a/stow/.local/bin/capture-video-desktop b/stow/.local/bin/capture-video-desktop
--- a/stow/.local/bin/capture-video-desktop
+++ b/stow/.local/bin/capture-video-desktop
@@ -29,39 +29,38 @@ Environment Variables:
     FILE_TYPE    extension to use for output file name (default: $file_type)
 "
 
+usage() {
+    echo "$usage" >&2
+    exit 0
+}
+
+die() {
+    echo "$me: $*" >&2
+    exit 1
+}
+
 unset OPTIND OPTARG
 while getopts ":huwsm" option; do
     case $option in
-    h)
-        echo "$usage" >&2
-        exit 0
-        ;;
-
+    h) usage ;;
     u)
         name="window"
         geometry=$(xwinrect -id "$(active-window)")
         ;;
-
     w)
         name="window"
         geometry=$(xwinrect -id "$(selected-window)")
         ;;
-
     s)
         name="region"
         geometry=$(xrectsel)
         ;;
-
     m)
         name="region"
         follow_mouse=1
         geometry=$(xrectsel)
         ;;
-
-    *)
-        echo "invalid option '$option'" >&2
-        exit 1
-        ;;
+    *) die "invalid option '$option'" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -79,9 +78,9 @@ options=(-hide_banner -loglevel error)
 options+=(-y -f x11grab)
 
 options+=(-draw_mouse 0)
-[[ $follow_mouse ]] && options+=(-follow_mouse "$padding")
+[[ -n $follow_mouse ]] && options+=(-follow_mouse "$padding")
 
-[[ ! $geometry ]] && geometry=$(xwinrect -root)
+[[ -z $geometry ]] && geometry=$(xwinrect -root)
 
 size=${geometry%%+*}
 top_left=${geometry#*+}
@@ -91,7 +90,7 @@ options+=(-s "$size" -i "${DISPLAY}+${left%+*},${top#*+}")
 
 options+=(-f alsa -i default)
 
-[[ $DURATION ]] && options+=(-t "$DURATION")
+[[ -n $DURATION ]] && options+=(-t "$DURATION")
 
 canberra-gtk-play -l "$delay" -i message-new-instant
 
