Prefer printf to echo

diff --git a/stow/.local/bin/capture-image-camera b/stow/.local/bin/capture-image-camera
--- a/stow/.local/bin/capture-image-camera
+++ b/stow/.local/bin/capture-image-camera
@@ -34,7 +34,7 @@ Arguments:
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
@@ -45,7 +45,7 @@ while getopts ":d:D:N:E:h" option; do
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
@@ -71,4 +71,4 @@ notify-send -i media-record \
     "Captured photo from camera" \
     "<u>${output_file/$HOME/\~}</u>" &
 
-echo "$output_file"
+printf "%s\n" "$output_file"
diff --git a/stow/.local/bin/capture-image-desktop b/stow/.local/bin/capture-image-desktop
--- a/stow/.local/bin/capture-image-desktop
+++ b/stow/.local/bin/capture-image-desktop
@@ -37,7 +37,7 @@ Arguments:
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
@@ -50,7 +50,7 @@ while getopts ":g:sd:D:N:E:h" option; do
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
@@ -78,4 +78,4 @@ notify-send -i media-record \
     "Captured image of desktop" \
     "<u>${output_file/$HOME/\~}</u>" &
 
-echo "$output_file"
+printf "%s\n" "$output_file"
diff --git a/stow/.local/bin/capture-video-camera b/stow/.local/bin/capture-video-camera
--- a/stow/.local/bin/capture-video-camera
+++ b/stow/.local/bin/capture-video-camera
@@ -44,7 +44,7 @@ Arguments:
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
@@ -58,7 +58,7 @@ while getopts ":ai:d:t:D:N:E:h" option; do
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
@@ -69,7 +69,7 @@ ffmpeg_stdin=$XDG_RUNTIME_DIR/$name-ffmpeg-stdin
 
 if [[ -v 1 && $1 == stop ]]; then
     if [[ -f $ffmpeg_stdin ]]; then
-        echo "q" >>"$ffmpeg_stdin"
+        printf "q\n" >>"$ffmpeg_stdin"
     fi
     exit 0
 fi
@@ -104,7 +104,7 @@ if ! tty -s; then
     trap 'rm -f "$ffmpeg_stdin"' INT TERM EXIT
     "${ffmpeg_command[@]}" <"$ffmpeg_stdin"
 else
-    echo "Press 'q' at any time to stop recording..." >&2
+    printf "Press 'q' at any time to stop recording...\n"
     "${ffmpeg_command[@]}"
 fi
 
@@ -114,4 +114,4 @@ notify-send -i media-record \
     "Captured camera video ${capture_audio:+ (with microphone audio)}" \
     "<u>${output_file/$HOME/\~}</u>" &
 
-echo "$output_file"
+printf "%s\n" "$output_file"
diff --git a/stow/.local/bin/capture-video-desktop b/stow/.local/bin/capture-video-desktop
--- a/stow/.local/bin/capture-video-desktop
+++ b/stow/.local/bin/capture-video-desktop
@@ -48,7 +48,7 @@ Arguments:
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
@@ -72,7 +72,7 @@ while getopts ":g:sM:mad:t:D:N:E:h" option; do
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
@@ -83,7 +83,7 @@ ffmpeg_stdin=$XDG_RUNTIME_DIR/$name-ffmpeg-stdin
 
 if [[ -v 1 && $1 == stop ]]; then
     if [[ -f $ffmpeg_stdin ]]; then
-        echo "q" >>"$ffmpeg_stdin"
+        printf "q\n" >>"$ffmpeg_stdin"
     fi
     exit 0
 fi
@@ -132,7 +132,7 @@ if ! tty -s; then
     trap 'rm -f "$ffmpeg_stdin"' INT TERM EXIT
     "${ffmpeg_command[@]}" <"$ffmpeg_stdin"
 else
-    echo "Press 'q' at any time to stop recording..." >&2
+    printf "Press 'q' at any time to stop recording...\n"
     "${ffmpeg_command[@]}"
 fi
 
@@ -142,4 +142,4 @@ notify-send -i media-record \
     "Captured desktop video${capture_audio:+ (with microphone audio)}" \
     "<u>${output_file/$HOME/\~}</u>" &
 
-echo "$output_file"
+printf "%s\n" "$output_file"
diff --git a/stow/.local/bin/dmenu-pass b/stow/.local/bin/dmenu-pass
--- a/stow/.local/bin/dmenu-pass
+++ b/stow/.local/bin/dmenu-pass
@@ -23,7 +23,7 @@ In all cases, the password is copied to the clipboard.
 pass_dir=${PASSWORD_STORE_DIR:-$HOME/.password-store}
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
@@ -32,7 +32,7 @@ pass_names() {
         while IFS= read -r -d'' file; do
             name=${file#"$pass_dir"/}
             name=${name%.gpg}
-            echo "$name"
+            printf "%s\n" "$name"
         done < <(find -L "$pass_dir" -type f -name "*.gpg" -print0)
     fi
 }
@@ -41,7 +41,7 @@ while getopts ":n:h" option; do
     case $option in
     n) length=$OPTARG ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
diff --git a/stow/.local/bin/enable-touchpad b/stow/.local/bin/enable-touchpad
--- a/stow/.local/bin/enable-touchpad
+++ b/stow/.local/bin/enable-touchpad
@@ -9,7 +9,7 @@ device_name() {
 }
 
 choose_device() {
-    echo "Enter the device id to enable:"
+    printf "Enter the device ID to enable:"
 
     readarray -t ids < <(
         xinput --list | grep -v XTEST |
@@ -19,17 +19,17 @@ choose_device() {
 
     local id
     for id in "${ids[@]}"; do
-        echo "$id) $(device_name "$id")"
+        printf "%s) %s\n" "$id" "$(device_name "$id")"
     done
 
     read -r -p "${PS3:-#? }" id
 
     if ! printf "%s\n" "${ids[@]}" | grep -q "^$id$"; then
-        echo "ERROR: Invalid device ID" >&2
+        printf "ERROR: Invalid device ID" >&2
         exit 1
     fi
 
-    echo "$id"
+    printf "%s\n" "$id"
 }
 
 id=${1:-$(choose_device)}
@@ -52,4 +52,4 @@ Section "InputClass"
 EndSection
 EOF
 
-echo "Change options in: $conf"
+printf "Change options in: %s\n" "$conf"
diff --git a/stow/.local/bin/rofi-snip b/stow/.local/bin/rofi-snip
--- a/stow/.local/bin/rofi-snip
+++ b/stow/.local/bin/rofi-snip
@@ -20,7 +20,7 @@ Actions:
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
@@ -46,7 +46,7 @@ while getopts ":C:h" option; do
     case $option in
     C) snip_options+=(-C "$OPTARG") ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "invalid option: $OPTARG" ;;
diff --git a/stow/.local/bin/snip b/stow/.local/bin/snip
--- a/stow/.local/bin/snip
+++ b/stow/.local/bin/snip
@@ -28,12 +28,12 @@ Actions:
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
 snippet_file() {
-    echo "$config_dir/${1:?Missing snippet name}"
+    printf "%s/%s" "$config_dir" "${1:?Missing snippet name}"
 }
 
 snippet_file_required() {
@@ -44,7 +44,7 @@ snippet_file_required() {
         die "Snippet '$name' does not exist"
     fi
 
-    echo "$file"
+    printf "%s\n" "$file"
 }
 
 do_list() {
@@ -82,7 +82,7 @@ while getopts ":C:h" option; do
     case $option in
     C) config_dir=$OPTARG ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
diff --git a/stow/.local/bin/timer b/stow/.local/bin/timer
--- a/stow/.local/bin/timer
+++ b/stow/.local/bin/timer
@@ -21,7 +21,7 @@ See --date option in date(1) for the definition of TIMESPEC.
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
@@ -29,7 +29,7 @@ while getopts ":n:h" option; do
     case $option in
     n) name=$OPTARG ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
diff --git a/stow/.local/bin/udiskie-add-keyfile b/stow/.local/bin/udiskie-add-keyfile
--- a/stow/.local/bin/udiskie-add-keyfile
+++ b/stow/.local/bin/udiskie-add-keyfile
@@ -25,7 +25,7 @@ If KEYFILE is not copied with -c, it will be used in the original location.
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
@@ -34,7 +34,7 @@ while getopts ":cC:h" option; do
     c) copy_keyfile=1 ;;
     C) config_dir=$OPTARG ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
diff --git a/stow/.local/bin/xpwd b/stow/.local/bin/xpwd
--- a/stow/.local/bin/xpwd
+++ b/stow/.local/bin/xpwd
@@ -20,7 +20,7 @@ If no window is selected with -w or ID, then the current window is used.
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
@@ -33,7 +33,7 @@ tmux_window_id() {
 tmux_session_id() {
     while IFS= read -r -d $'\n' session_id; do
         if [[ $(tmux_window_id "$session_id") == "${1:?Missing window ID}" ]]; then
-            echo "$session_id"
+            printf "%s\n" "$session_id"
             return 0
         fi
     done < <(tmux list-sessions -F '#{session_id}')
@@ -64,7 +64,7 @@ while getopts ":scnh" option; do
     c) copy_path_to_clipboard=1 ;;
     n) use_notifications=1 ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
@@ -131,4 +131,4 @@ if [[ -v copy_path_to_clipboard ]]; then
     fi
 fi
 
-echo "$cwd"
+printf "%s\n" "$cwd"
