Tinkering

diff --git a/stow/.local/bin/capture-image-camera b/stow/.local/bin/capture-image-camera
--- a/stow/.local/bin/capture-image-camera
+++ b/stow/.local/bin/capture-image-camera
@@ -29,7 +29,7 @@ usage() {
 }
 
 die() {
-    echo "$me: $*" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
@@ -42,7 +42,8 @@ while getopts ":h" option; do
 done && shift $((OPTIND - 1))
 unset option OPTIND OPTARG
 
-file=${1:-$(xdg-user-dir PICTURES)/camera-$(date +%s).$file_type}
+timestamp=$(date --iso-8601=seconds)
+file=${1:-$(xdg-user-dir PICTURES)/camera-$timestamp.$file_type}
 mkdir -p "$(dirname "$file")"
 
 options=(-hide_banner -loglevel error)
diff --git a/stow/.local/bin/capture-image-desktop b/stow/.local/bin/capture-image-desktop
--- a/stow/.local/bin/capture-image-desktop
+++ b/stow/.local/bin/capture-image-desktop
@@ -28,14 +28,13 @@ usage() {
 }
 
 die() {
-    echo "$me: $*" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
 unset OPTIND OPTARG
 while getopts ":huws" option; do
     case $option in
-    h) usage ;;
     u)
         name="window"
         geometry=$(xwinrect -id "$(active-window)")
@@ -48,17 +47,21 @@ while getopts ":huws" option; do
         name="region"
         geometry=$(xrectsel)
         ;;
+    h) usage ;;
     *) die "invalid option: $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 unset option OPTIND OPTARG
 
-file=${1:-$(xdg-user-dir PICTURES)/desktop-${name:+$name-}$(date +%s).$file_type}
+timestamp=$(date --iso-8601=seconds)
+file=${1:-$(xdg-user-dir PICTURES)/desktop-${name:+$name-}$timestamp.$file_type}
 mkdir -p "$(dirname "$file")"
 
 options=(-window root)
 
-[[ -v geometry ]] && options+=(-crop "$geometry")
+if [[ -v geometry ]]; then
+    options+=(-crop "$geometry")
+fi
 
 import "${options[@]}" "$file"
 
diff --git a/stow/.local/bin/capture-video-camera b/stow/.local/bin/capture-video-camera
--- a/stow/.local/bin/capture-video-camera
+++ b/stow/.local/bin/capture-video-camera
@@ -30,7 +30,7 @@ usage() {
 }
 
 die() {
-    echo "$me: $*" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
@@ -46,17 +46,22 @@ unset option OPTIND OPTARG
 ffmpeg_stdin=$XDG_RUNTIME_DIR/$me-ffmpeg-stdin
 
 if [[ $1 == stop ]]; then
-    [[ -f $ffmpeg_stdin ]] && echo "q" >>"$ffmpeg_stdin"
+    if [[ -f $ffmpeg_stdin ]]; then
+        echo "q" >>"$ffmpeg_stdin"
+    fi
     exit 0
 fi
 
-file=${1:-$(xdg-user-dir PICTURES)/camera-$(date +%s).$file_type}
+timestamp=$(date --iso-8601=seconds)
+file=${1:-$(xdg-user-dir PICTURES)/camera-$timestamp.$file_type}
 mkdir -p "$(dirname "$file")"
 
 options=(-hide_banner -loglevel error)
 options+=(-y -f v4l2 -i "$device" -f alsa -i default)
 
-[[ -n $DURATION ]] && options+=(-t "$DURATION")
+if [[ -n $DURATION ]]; then
+    options+=(-t "$DURATION")
+fi
 
 canberra-gtk-play -l "$delay" -i message
 
diff --git a/stow/.local/bin/capture-video-desktop b/stow/.local/bin/capture-video-desktop
--- a/stow/.local/bin/capture-video-desktop
+++ b/stow/.local/bin/capture-video-desktop
@@ -35,14 +35,13 @@ usage() {
 }
 
 die() {
-    echo "$me: $*" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
 unset OPTIND OPTARG
 while getopts ":huwsm" option; do
     case $option in
-    h) usage ;;
     u)
         name="window"
         geometry=$(xwinrect -id "$(active-window)")
@@ -60,6 +59,7 @@ while getopts ":huwsm" option; do
         follow_mouse=1
         geometry=$(xrectsel)
         ;;
+    h) usage ;;
     *) die "invalid option: $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
@@ -68,20 +68,27 @@ unset option OPTIND OPTARG
 ffmpeg_stdin=$XDG_RUNTIME_DIR/$me-ffmpeg-stdin
 
 if [[ $1 == stop ]]; then
-    [[ -f $ffmpeg_stdin ]] && echo "q" >>"$ffmpeg_stdin"
+    if [[ -f $ffmpeg_stdin ]]; then
+        echo "q" >>"$ffmpeg_stdin"
+    fi
     exit 0
 fi
 
-file=${1:-$(xdg-user-dir VIDEOS)/desktop-${name:+$name-}$(date +%s).$file_type}
+timestamp=$(date --iso-8601=seconds)
+file=${1:-$(xdg-user-dir VIDEOS)/desktop-${name:+$name-}$timestamp.$file_type}
 mkdir -p "$(dirname "$file")"
 
 options=(-hide_banner -loglevel error)
 options+=(-y -f x11grab)
 
 options+=(-draw_mouse 0)
-[[ -n $follow_mouse ]] && options+=(-follow_mouse "$padding")
+if [[ -n $follow_mouse ]]; then
+    options+=(-follow_mouse "$padding")
+fi
 
-[[ -z $geometry ]] && geometry=$(xwinrect -root)
+if [[ -z $geometry ]]; then
+    geometry=$(xwinrect -root)
+fi
 
 size=${geometry%%+*}
 top_left=${geometry#*+}
@@ -91,7 +98,9 @@ options+=(-s "$size" -i "${DISPLAY}+${left%+*},${top#*+}")
 
 options+=(-f alsa -i default)
 
-[[ -n $DURATION ]] && options+=(-t "$DURATION")
+if [[ -n $DURATION ]]; then
+    options+=(-t "$DURATION")
+fi
 
 canberra-gtk-play -l "$delay" -i message
 
diff --git a/stow/.local/bin/rofi-snip b/stow/.local/bin/rofi-snip
--- a/stow/.local/bin/rofi-snip
+++ b/stow/.local/bin/rofi-snip
@@ -22,7 +22,7 @@ usage() {
 }
 
 die() {
-    echo "$me: $*" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
@@ -36,8 +36,8 @@ option_names["d"]="delete"
 unset OPTIND OPTARG
 while getopts ":hecstd" option; do
     case $option in
-    h) usage ;;
     e | c | s | t | d) snip_option=$option ;;
+    h) usage ;;
     *) die "invalid option: $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
