Tinkering

diff --git a/stow/.local/bin/capture-video-camera b/stow/.local/bin/capture-video-camera
--- a/stow/.local/bin/capture-video-camera
+++ b/stow/.local/bin/capture-video-camera
@@ -2,26 +2,45 @@
 
 set -eu
 
-delay=${DELAY:-3}
-device=${DEVICE:-/dev/video0}
-file_type=${FILE_TYPE:-mp4}
+delay=0
+device=/dev/video0
+directory=$(xdg-user-dir VIDEOS)
+file_name=camera_%FT%T%:z
+file_type=mp4
 
-me=${0##*/}
-usage="Capture video from a camera.
+name=${0##*/}
+usage="Capture video from a camera device.
 
-Usage: $me [OPTIONS] [FILE | stop]
+Usage:
+    $name [OPTIONS] [FILE | 'stop']
     
 Options:
-    -h           show this help message
+    -a              also capture audio from microphone
+
+    -i DEVICE       capture input from device
+                    (default: $device)
+
+    -d NUMBER       number of seconds to wait before starting capture
+                    (default: $delay)
+
+    -t NUMBER       number of seconds to capture
+                    (default: record indefinitely)
+
+    -D DIRECTORY    directory in which to store default output file
+                    (default: $directory)
+
+    -N FILENAME     filename to use for default output file
+                    (default: $file_name)
+
+    -E EXTENSION    extension to use for default output file
+                    (default: $file_type)
 
 Arguments:
-    FILE         output capture to FILE
-    stop         stop recording
+    FILE            output file (used instead of default)
+                    formats any sequences recognized by strftime
+                    (default: $directory/$file_name.$file_type)
 
-Environment Variables:
-    DELAY        number of seconds to delay capture (default: $delay)
-    DEVICE       video device to use for capture (default: $device) 
-    FILE_TYPE    extension to use for capture file name (default: $file_type)
+    'stop'          stop any recording session already in progress
 "
 
 usage() {
@@ -34,42 +53,67 @@ die() {
     exit 1
 }
 
-unset OPTIND OPTARG
-while getopts ":h" option; do
+while getopts ":ai:d:t:D:N:E:h" option; do
     case $option in
+    a) capture_audio=1 ;;
+    i) device=$OPTARG ;;
+    d) delay=$OPTARG ;;
+    t) duration=$OPTARG ;;
+    D) directory=$OPTARG ;;
+    N) file_name=$OPTARG ;;
+    E) file_type=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option: $OPTARG" ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
-unset option OPTIND OPTARG
 
-ffmpeg_stdin=$XDG_RUNTIME_DIR/$me-ffmpeg-stdin
+ffmpeg_stdin=$XDG_RUNTIME_DIR/$name-ffmpeg-stdin
 
-if [[ $1 == stop ]]; then
+if [[ -v 1 && $1 == stop ]]; then
     if [[ -f $ffmpeg_stdin ]]; then
         echo "q" >>"$ffmpeg_stdin"
     fi
     exit 0
 fi
 
-timestamp=$(date --iso-8601=seconds)
-file=${1:-$(xdg-user-dir PICTURES)/camera-$timestamp.$file_type}
-mkdir -p "$(dirname "$file")"
+output_file=$(date +"${1:-$directory/$file_name.$file_type}")
 
 options=(-hide_banner -loglevel error)
-options+=(-y -f v4l2 -i "$device" -f alsa -i default)
 
-if [[ -n $DURATION ]]; then
-    options+=(-t "$DURATION")
+options+=(-y -f v4l2 -i "$device")
+
+if [[ -v capture_audio ]]; then
+    options+=(-f alsa -i default)
 fi
 
-canberra-gtk-play -l "$delay" -i message
+if [[ -v duration ]]; then
+    options+=(-t "$duration")
+fi
 
-touch "$ffmpeg_stdin"
-trap 'rm -f "$ffmpeg_stdin"' INT TERM EXIT
-ffmpeg "${options[@]}" "$file" <"$ffmpeg_stdin"
+if [[ -v delay ]]; then
+    canberra-gtk-play -l "$delay" -i message
+fi
+
+# If not connected to a TTY, tell ffmpeg to get its stdin from a runtime file.
+# This way, recording can be stopped remotely by writing 'q' to the file.
+# For this script, a shortcut is to give "stop" as the first argument.
+
+mkdir -p "$(dirname "$output_file")"
+ffmpeg_command=(ffmpeg "${options[@]}" "$output_file")
+
+if ! tty -s; then
+    touch "$ffmpeg_stdin"
+    trap 'rm -f "$ffmpeg_stdin"' INT TERM EXIT
+    "${ffmpeg_command[@]}" <"$ffmpeg_stdin"
+else
+    echo "Press 'q' at any time to stop recording..." >&2
+    "${ffmpeg_command[@]}"
+fi
 
 canberra-gtk-play -i screen-capture &
-notify-send -i media-record "Captured Video" "<u>${file/$HOME/\~}</u>" &
 
-echo "$file"
+notify-send -i media-record \
+    "Captured camera video ${capture_audio:+ (with microphone audio)}" \
+    "<u>${output_file/$HOME/\~}</u>" &
+
+echo "$output_file"
diff --git a/stow/.local/bin/capture-video-desktop b/stow/.local/bin/capture-video-desktop
--- a/stow/.local/bin/capture-video-desktop
+++ b/stow/.local/bin/capture-video-desktop
@@ -2,31 +2,49 @@
 
 set -eu
 
-delay=${DELAY:-1}
-file_type=${FILE_TYPE:-mp4}
-padding=${PADDING:-centered}
+delay=0
+directory=$(xdg-user-dir VIDEOS)
+file_name=desktop_%FT%T%:z
+file_type=mp4
 
-me=${0##*/}
+name=${0##*/}
 usage="Capture video of the desktop.
 
-Usage: $me [OPTIONS] [FILE | stop]
+Usage:
+    $name [OPTIONS] [FILE | 'stop']
     
 Options:
-    -h           show this help message
-    -u           capture the current window
-    -w           click to select a window to capture
-    -s           drag to select a region to capture
-    -m           drag to size a viewport that follows the mouse
+    -g GEOMETRY     geometry of region to capture
+
+    -s              select window or region to capture
+
+    -a              also capture audio from microphone
+
+    -M PADDING      drag to size a viewport region that follows mouse
+                    mouse cursor stays at least PADDING pixels from edge
+                    if PADDING is 'centered', keep mouse cursor centered
+
+    -d NUMBER       number of seconds to wait before starting capture
+                    (default: $delay)
+
+    -t NUMBER       number of seconds to capture
+                    (default: record indefinitely)
+
+    -D DIRECTORY    directory in which to store default output file
+                    (default: $directory)
+
+    -N FILENAME     filename to use for default output file
+                    (default: $file_name)
+
+    -E EXTENSION    extension to use for default output file
+                    (default: $file_type)
 
 Arguments:
-    FILE         output capture to FILE
-    stop         stop recording
+    FILE            output file (used instead of default)
+                    formats any sequences recognized by strftime
+                    (default: $directory/$file_name.$file_type)
 
-Environment Variables:
-    DELAY        number of seconds to delay capture (default: $delay)
-    DURATION     number of seconds to record (default: record indefinitely)
-    PADDING      number of pixels to pad region used with -m (default: $padding)
-    FILE_TYPE    extension to use for output file name (default: $file_type)
+    'stop'          stop any recording session already in progress
 "
 
 usage() {
@@ -39,55 +57,51 @@ die() {
     exit 1
 }
 
-unset OPTIND OPTARG
-while getopts ":huwsm" option; do
+select_geometry() {
+    slop -f "%wx%h+%x+%y"
+}
+
+while getopts ":g:sM:mad:t:D:N:E:h" option; do
     case $option in
-    u)
-        name="window"
-        geometry=$(xwinrect -id "$(active-window)")
+    g) geometry=$OPTARG ;;
+    s) geometry=$(select_geometry) ;;
+    M)
+        follow_mouse=$OPTARG
+        geometry=$(select_geometry)
         ;;
-    w)
-        name="window"
-        geometry=$(xwinrect -id "$(selected-window)")
-        ;;
-    s)
-        name="region"
-        geometry=$(xrectsel)
-        ;;
-    m)
-        name="region"
-        follow_mouse=1
-        geometry=$(xrectsel)
-        ;;
+    m) draw_mouse=1 ;;
+    a) capture_audio=1 ;;
+    d) delay=$OPTARG ;;
+    t) duration=$OPTARG ;;
+    D) directory=$OPTARG ;;
+    N) file_name=$OPTARG ;;
+    E) file_type=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option: $OPTARG" ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
-unset option OPTIND OPTARG
 
-ffmpeg_stdin=$XDG_RUNTIME_DIR/$me-ffmpeg-stdin
+ffmpeg_stdin=$XDG_RUNTIME_DIR/$name-ffmpeg-stdin
 
-if [[ $1 == stop ]]; then
+if [[ -v 1 && $1 == stop ]]; then
     if [[ -f $ffmpeg_stdin ]]; then
         echo "q" >>"$ffmpeg_stdin"
     fi
     exit 0
 fi
 
-timestamp=$(date --iso-8601=seconds)
-file=${1:-$(xdg-user-dir VIDEOS)/desktop-${name:+$name-}$timestamp.$file_type}
-mkdir -p "$(dirname "$file")"
+output_file=$(date +"${1:-$directory/$file_name.$file_type}")
 
-options=(-hide_banner -loglevel error)
-options+=(-y -f x11grab)
+options=(-hide_banner -loglevel warning)
 
-options+=(-draw_mouse 0)
-if [[ -n $follow_mouse ]]; then
-    options+=(-follow_mouse "$padding")
+options+=(-y -f x11grab -draw_mouse "${draw_mouse:-0}")
+
+if [[ -v follow_mouse ]]; then
+    options+=(-follow_mouse "$follow_mouse")
 fi
 
-if [[ -z $geometry ]]; then
-    geometry=$(xwinrect -root)
+if [[ ! -v geometry ]]; then
+    geometry=$(xwininfo -root | grep -w geometry | awk '{print $2}')
 fi
 
 size=${geometry%%+*}
@@ -96,19 +110,38 @@ left=${top_left%+*}
 top=${top_left#*+}
 options+=(-s "$size" -i "${DISPLAY}+${left%+*},${top#*+}")
 
-options+=(-f alsa -i default)
-
-if [[ -n $DURATION ]]; then
-    options+=(-t "$DURATION")
+if [[ -v capture_audio ]]; then
+    options+=(-f alsa -i default)
 fi
 
-canberra-gtk-play -l "$delay" -i message
+if [[ -v duration ]]; then
+    options+=(-t "$duration")
+fi
 
-touch "$ffmpeg_stdin"
-trap 'rm -f "$ffmpeg_stdin"' INT TERM EXIT
-ffmpeg "${options[@]}" "$file" <"$ffmpeg_stdin"
+if [[ -v delay ]]; then
+    canberra-gtk-play -l "$delay" -i message
+fi
+
+# If not connected to a TTY, tell ffmpeg to get its stdin from a runtime file.
+# This way, recording can be stopped remotely by writing 'q' to the file.
+# For this script, a shortcut is to give "stop" as the first argument.
+
+mkdir -p "$(dirname "$output_file")"
+ffmpeg_command=(ffmpeg "${options[@]}" "$output_file")
+
+if ! tty -s; then
+    touch "$ffmpeg_stdin"
+    trap 'rm -f "$ffmpeg_stdin"' INT TERM EXIT
+    "${ffmpeg_command[@]}" <"$ffmpeg_stdin"
+else
+    echo "Press 'q' at any time to stop recording..." >&2
+    "${ffmpeg_command[@]}"
+fi
 
 canberra-gtk-play -i camera-shutter &
-notify-send -i media-record "Captured Screencast" "<u>${file/$HOME/\~}</u>" &
 
-echo "$file"
+notify-send -i media-record \
+    "Captured desktop video${capture_audio:+ (with microphone audio)}" \
+    "<u>${output_file/$HOME/\~}</u>" &
+
+echo "$output_file"
diff --git a/stow/.local/bin/disable-kernel-module b/stow/.local/bin/disable-kernel-module
--- a/stow/.local/bin/disable-kernel-module
+++ b/stow/.local/bin/disable-kernel-module
@@ -7,7 +7,7 @@ set -eu
 mod_name=$1
 
 if ! modprobe --show --quiet "$mod_name"; then
-    echo "invalid module: $mod_name" >&2
+    echo "Invalid module '$mod_name'" >&2
     exit 1
 fi
 
diff --git a/stow/.local/bin/snip b/stow/.local/bin/snip
--- a/stow/.local/bin/snip
+++ b/stow/.local/bin/snip
@@ -2,23 +2,30 @@
 
 set -eu
 
-me=${0##*/}
-usage="Interact with text snippets.
+config_dir=${XDG_CONFIG_HOME:-$HOME/.config}/snip
 
-Usage: $me [-h] [-l] [-pecst NAME]
+name=${0##*/}
+usage="Manage text snippets.
+
+Usage:
+    $name [OPTIONS] ACTION [NAME]
 
 Options:
-    -h         show this help message
-    -l         list snippets
-    -p NAME    print snippet to stdout
-    -e NAME    edit snippet in preferred editor
-    -c NAME    copy snippet to clipboard
-    -s NAME    save clipboard to snippet
-    -t NAME    type snippet in active window
-    -d NAME    delete snippet
-"
+    -C DIRECTORY    directory in which to store snippets
+                    (default: $config_dir)
 
-snippets_dir=${XDG_CONFIG_HOME:-$HOME/.config}/snip/snippets
+Arguments:
+    ACTION          perform action on snippet
+    NAME            snippet on which to perform action
+
+Actions:
+    list            print snippet names to stdout
+    path            print snippet path to stdout
+    read            dump snippet to stdout
+    write           create snippet from stdin
+    edit            open snippet in editor
+    delete          delete snippet
+"
 
 usage() {
     echo "$usage" >&2
@@ -26,71 +33,86 @@ usage() {
 }
 
 die() {
-    echo "$me: $*" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
-list_snippets() {
-    if [[ -d $snippets_dir ]]; then
-        find "$snippets_dir" -type f -exec basename {} \;
-    fi
-}
-
 snippet_file() {
-    echo "$snippets_dir/${1:?missing snippet name}"
+    echo "$config_dir/${1:?missing snippet name}"
 }
 
 snippet_file_required() {
     local file
     file=$(snippet_file "$1")
-    [[ -f $file ]] || die "snippet '$name' not found"
+
+    if [[ ! -f $file ]]; then
+        die "Snippet '$name' does not exist"
+    fi
+
     echo "$file"
 }
 
-print_snippet() {
+do_list() {
+    if [[ -d $config_dir ]]; then
+        find "$config_dir" -type f -printf "%P\n"
+    fi
+}
+
+do_path() {
+    snippet_file "$1"
+}
+
+do_write() {
+    local file
+    file=$(snippet_file "$1")
+
+    mkdir -p "$(dirname "$file")"
+
+    cat >"$file"
+}
+
+do_read() {
     cat "$(snippet_file_required "$1")"
 }
 
-edit_snippet() {
-    mkdir -p "$snippets_dir"
-    exec "${VISUAL:-$EDITOR}" "$(snippet_file "$1")"
+do_edit() {
+    exec "${VISUAL:-$EDITOR}" "$(snippet_file_required "$1")"
 }
 
-copy_snippet() {
-    local name=$1
-    xsel --input --clipboard <"$(snippet_file_required "$name")"
-    notify-send -i edit-copy "Snippet Text for '$name' Copied to the Clipboard"
-}
-
-save_snippet() {
-    local name=$1
-    mkdir -p "$snippets_dir"
-    xsel --output --clipboard >"$(snippet_file "$name")"
-    notify-send -i document-save "Snippet Text for '$name' Saved from the Clipboard"
-}
-
-type_snippet() {
-    xdotool type --clearmodifiers --delay 25 --file "$(snippet_file_required "$1")"
-}
-
-delete_snippet() {
+do_delete() {
     rm -f "$(snippet_file_required "$1")"
 }
 
-(($# == 0)) && set -- -h
-
-unset OPTIND OPTARG
-while getopts ":hlp:e:c:s:t:d:" option; do
+while getopts ":C:h" option; do
     case $option in
-    l) list_snippets ;;
-    p) print_snippet "$OPTARG" ;;
-    e) edit_snippet "$OPTARG" ;;
-    c) copy_snippet "$OPTARG" ;;
-    s) save_snippet "$OPTARG" ;;
-    t) type_snippet "$OPTARG" ;;
-    d) delete_snippet "$OPTARG" ;;
+    C) config_dir=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option: $OPTARG" ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
-unset option OPTIND OPTARG
+
+if [[ ! -v 1 ]]; then
+    die "Missing action"
+fi
+
+action=$1
+shift
+
+case $action in
+list | path | read | write | edit | delete) ;;
+*) die "Invalid action '$action'" ;;
+esac
+
+if [[ $action == list ]]; then
+    do_list
+    exit 0
+fi
+
+if [[ ! -v 1 ]]; then
+    die "Missing snippet name"
+fi
+
+snippet_name=$1
+shift
+
+do_"$action" "$snippet_name"
diff --git a/stow/.local/bin/timer b/stow/.local/bin/timer
--- a/stow/.local/bin/timer
+++ b/stow/.local/bin/timer
@@ -2,22 +2,22 @@
 
 set -eu
 
-me=${0##*/}
+name=${0##*/}
 usage="Sound an alarm after a specified amount of time.
 
-Usage: $me [-h] [-n NAME] TIMESPEC
+Usage:
+    $name [OPTIONS] TIMESPEC
 
 Options:
-    -h           show this help message
-    -n NAME      give the timer a descriptive name
-
-See the --date option in date(1) for definition of TIMESPEC.
+    -n NAME    descriptive name for timer
 
 Examples:
     timer 1 minute
     timer -n laundry 45 minutes
     timer -n 'boat tour' 3 hours
     timer -n 'very specific' now + 1 hour + 10 minutes
+
+See --date option in date(1) for the definition of TIMESPEC.
 "
 
 usage() {
@@ -26,25 +26,24 @@ usage() {
 }
 
 die() {
-    echo "$me: $*" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
-name=
-unset OPTIND OPTARG
-while getopts ":hn:" option; do
+while getopts ":n:h" option; do
     case $option in
     n) name=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option: $OPTARG" ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
-unset option OPTIND OPTARG
 
-(($# > 0)) || die "missing time specification"
+if (($# == 0)); then
+    die "Missing time specification"
+fi
 
 at "$(date -d "$*" +"%H:%M %Y-%m-%d")" <<-EOF
 export DISPLAY=$DISPLAY
 canberra-gtk-play -i alarm-clock-elapsed &
-notify-send -u critical "Timer Elapsed" "$name"
+notify-send -u critical "Timer elapsed" "${name:-}"
 EOF
diff --git a/stow/.local/bin/xpwd b/stow/.local/bin/xpwd
--- a/stow/.local/bin/xpwd
+++ b/stow/.local/bin/xpwd
@@ -2,22 +2,21 @@
 
 set -eu
 
-me=${0##*/}
-usage="
-Gets the working directory of a window.
+name=${0##*/}
+usage="Print the working directory of a window.
 
-Usage: $me [-h] [-cnw] [WINDOW_ID]
+Usage:
+    $name [OPTIONS] [ID]
 
 Options:
-    -h    show this help message
-    -c    copy the path to the clipboard
-    -n    notify the user about the copy
-    -w    click to select the window to use
+    -c    copy path to clipboard
+    -n    notify user about copy
+    -s    select window to use by clicking it
 
 Arguments:
-    WINDOW_ID    id of a window to use (e.g. 0x1234567)
-
-If no window is selected with -w or WINDOW_ID, then the current window is used.
+    ID    identifier of a window to use (e.g. 0x1234567)
+                
+If no window is selected with -w or ID, then the current window is used.
 "
 
 usage() {
@@ -26,69 +25,61 @@ usage() {
 }
 
 die() {
-    echo "$me: $*" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
 tmux_window_id() {
-    local session_id=${1:?missing session id}
-
-    tmux showenv -t "$session_id" WINDOWID |
+    tmux showenv -t "${1:?missing session id}" WINDOWID |
         awk -F= '{print $2}' | tr -d '[:space:]' |
         xargs -r -I{} printf "0x%x" "{}"
 }
 
 tmux_session_id() {
-    local window_id=$1
-
-    readarray -t session_ids < <(tmux list-sessions -F '#{session_id}')
-
-    for session_id in "${session_ids[@]}"; do
-        if [[ "$(tmux_window_id "$session_id")" == "$window_id" ]]; then
+    while IFS= read -r -d $'\n' session_id; do
+        if [[ $(tmux_window_id "$session_id") == "${1:?missing window id}" ]]; then
             echo "$session_id"
             return 0
         fi
-    done
-
+    done < <(tmux list-sessions -F '#{session_id}')
     return 1
 }
 
 tmux_active_pane_pid() {
-    local window_id=${1:?missing window id}
-    local session_id
-
-    session_id=$(tmux_session_id "$window_id")
-
     tmux list-panes -F '#{session_id} #{pane_active} #{pane_pid}' |
-        grep -m1 "^$session_id 1 " |
+        grep -m1 "^$(tmux_session_id "$1") 1 " |
         awk '{print $NF}' | tr -d '[:space:]'
 }
 
-window_id=
-copy_path_to_clipboard=
-use_notifications=
-unset OPTIND OPTARG
-while getopts ":hwcn" option; do
+selected_window_id() {
+    xwininfo | grep -m1 "Window id" | awk '{print $4}'
+}
+
+active_window_id() {
+    xprop -root | grep -m1 _NET_ACTIVE_WINDOW | awk '{print $NF}'
+}
+
+pid_for_window_id() {
+    xprop -id "${1:?missing window id}" | grep -m1 PID | awk '{print $3}'
+}
+
+while getopts ":scnh" option; do
     case $option in
-    w) window_id=$(selected-window) ;;
+    s) window_id=$(selected_window_id) ;;
     c) copy_path_to_clipboard=1 ;;
     n) use_notifications=1 ;;
     h) usage ;;
-    *) die "invalid option: $OPTARG" ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
-unset option OPTIND OPTARG
 
-if [[ -z $window_id ]]; then
-    window_id=${1:-$(active-window)}
+if [[ ! -v window_id ]]; then
+    window_id=${1:-$(active_window_id)}
 fi
 
 cwd=$HOME # fallback
 
-window_pid=$(
-    xprop -id "$window_id" | grep -m1 PID |
-        awk -F= '{print $2}' | tr -d '[:space:]'
-)
+window_pid=$(pid_for_window_id "$window_id")
 
 if [[ -n $window_pid ]]; then
     readarray -t lines < <(
@@ -109,19 +100,23 @@ if [[ -n $window_pid ]]; then
 
         case $name in
         # If tmux is active in this window,
-        # cwd will be whatever it was when tmux was started.
-        # There could be multiple panes, each with its own pid and cwd.
+        # The current directory will be whatever it was when tmux was started.
+        # It's more likely that the directory you want is the active pane's.
         tmux*) pid=$(tmux_active_pane_pid "$window_id") ;;
 
-        # Programs like vim and ranger use other tools to do their work.
+        # Programs like vim and ranger spawn subprocesses to do their work.
         # These should never have their own window, so it's safe to ignore them.
         xsel | xclip | ueberzug) continue ;;
         esac
 
         cwd_link=/proc/$pid/cwd
-        [[ -e $cwd_link ]] || continue
+
+        if [[ ! -e $cwd_link ]]; then
+            continue
+        fi
 
         possible_cwd=$(readlink "$cwd_link")
+
         if [[ -d $possible_cwd ]]; then
             cwd=$possible_cwd
             break
@@ -129,11 +124,13 @@ if [[ -n $window_pid ]]; then
     done
 fi
 
-if [[ -n $copy_path_to_clipboard ]]; then
+if [[ -v copy_path_to_clipboard ]]; then
     xsel -ib <<<"$cwd"
-    if [[ -n $use_notifications ]]; then
-        notify-send -i edit-copy "Working directory copied to clipboard:" "$cwd"
+    if [[ -v use_notifications ]]; then
+        notify-send -i edit-copy \
+            "Working directory copied to clipboard" \
+            "$cwd"
     fi
 fi
 
-echo -n "$cwd"
+echo "$cwd"
