Clean up stdout/stderr usage

diff --git a/stow/.local/bin/enable-touchpad b/stow/.local/bin/enable-touchpad
--- a/stow/.local/bin/enable-touchpad
+++ b/stow/.local/bin/enable-touchpad
@@ -9,7 +9,7 @@ device_name() {
 }
 
 choose_device() {
-    echo "Enter the device id to enable:" >&2
+    echo "Enter the device id to enable:"
 
     readarray -t ids < <(
         xinput --list | grep -v XTEST |
@@ -19,13 +19,13 @@ choose_device() {
 
     local id
     for id in "${ids[@]}"; do
-        echo "$id) $(device_name "$id")" >&2
+        echo "$id) $(device_name "$id")"
     done
 
     read -r -p "${PS3:-#? }" id
 
     if ! printf "%s\n" "${ids[@]}" | grep -q "^$id$"; then
-        echo "${0##*/}: invalid device id" >&2
+        echo "ERROR: Invalid device ID" >&2
         exit 1
     fi
 
@@ -52,4 +52,4 @@ Section "InputClass"
 EndSection
 EOF
 
-echo "Change options in: $conf" >&2
+echo "Change options in: $conf"
