Tinkering

diff --git a/stow/.local/bin/timer b/stow/.local/bin/timer
--- a/stow/.local/bin/timer
+++ b/stow/.local/bin/timer
@@ -1,55 +1,49 @@
 #!/usr/bin/env bash
 
+set -e
+
 me=${0##*/}
 usage="Sound an alarm after a specified amount of time.
-Usage: $me [-h] <n>[dhms] # (days, hours, minutes, seconds)
-Usage examples:
-timer -n laundry 45m
-timer -n 'boat tour' 3h
+
+Usage: $me [-h] [-n NAME] TIMESPEC
+
+Options:
+    -h           show this help message
+    -n NAME      give the timer a descriptive name
+
+See the --date option in date(1) for definition of TIMESPEC.
+
+Examples:
+    timer 1 minute
+    timer -n laundry 45 minutes
+    timer -n 'boat tour' 3 hours
+    timer -n 'very specific' now + 1 hour + 10 minutes
 "
 
-seconds() {
-	local duration=$1
-	case $duration in
-		*[dhms])
-			unit=${duration:$((${#duration}-1)):1}
-			value=${duration%$unit}
-		;;
-		*) return 1
-	esac
-	case $unit in
-		s) in_secs=1 ;;
-		m) in_secs=60 ;;
-		h) in_secs=3600 ;;
-		d) in_secs=86400 ;;
-	esac
-	echo $(( value * in_secs ))
+usage() {
+    echo "$usage" >&2
+    exit 0
 }
 
-name=timer
-unset OPTIND
+die() {
+    echo "$me: $*" >&2
+    exit 1
+}
+
+unset name
+
 while getopts ":hn:" option; do
-	case $option in
-		n) name=$OPTARG ;;
-		h) echo "$usage" >&2; exit 0 ;;
-		*) echo "$usage" >&2; exit 1 ;;
-	esac
+    case $option in
+    h) usage ;;
+    n) name=$OPTARG ;;
+    *) die "invalid option '$option'" ;;
+    esac
 done && shift $((OPTIND - 1))
 
-# default to 30 sec
-duration=${1:-30s}
+(($# > 0)) || die "missing time specification"
 
-
-secs=$(seconds "${1:-30s}")
-w=${#secs}
-stop=$(date -d "$secs seconds" "+on %F at %-l:%M:%S%P")
-while true; do
-	remain=$(( secs - SECONDS ))
-	printf "%s ending %s: %*ss remaining\r" "$name" "$stop" "$w" $remain
-	(( remain <= 0 )) && break
-	sleep 1
-done
-echo
-
+at "$(date -d "$*" +"%H:%M %Y-%m-%d")" <<-EOF
+export DISPLAY=$DISPLAY
 canberra-gtk-play -i alarm-clock-elapsed &
-notify-send -u critical "Timer Elapsed" "$name ended after $duration"
+notify-send -u critical "Timer Elapsed" "$name"
+EOF
diff --git a/stow/.local/bin/xpwd b/stow/.local/bin/xpwd
--- a/stow/.local/bin/xpwd
+++ b/stow/.local/bin/xpwd
@@ -1,101 +1,133 @@
 #!/usr/bin/env bash
 
+set -e
+
+me=${0##*/}
 usage="
-Gets the working directory of the current window.
+Gets the working directory of a window.
 
-Optional dependencies:
-xsel, notification daemon
+Usage: $me [-h] [-cnw] [WINDOW_ID]
 
-Usage: ${0##*/} [-h] [-cnw]
+Options:
+    -h    show this help message
+    -c    copy the path to the clipboard
+    -n    notify the user about the copy
+    -w    click to select the window to use
+
+Arguments:
+    WINDOW_ID    id of a window to use (e.g. 0x1234567)
+
+If no window is selected with -w or WINDOW_ID, then the current window is used.
 "
 
-icon_set=/usr/share/icons/gnome/32x32
-icon=$icon_set/actions/edit-paste.png
+usage() {
+    echo "$usage" >&2
+    exit 0
+}
+
+die() {
+    echo "$me: $*" >&2
+    exit 1
+}
+
+tmux_window_id() {
+    local session_id=${1:?missing session id}
+
+    tmux showenv -t "$session_id" WINDOWID |
+        awk -F= '{print $2}' | tr -d '[:space:]' |
+        xargs -r -I{} printf "0x%x" "{}"
+}
 
 tmux_session_id() {
-    local win_id=$1
-    tmux list-sessions -F '#{session_id}' |
-        while read -r session_id; do
-            unset WINDOWID
-            eval "$(tmux showenv -t "$session_id" WINDOWID)"
-            session_win_id=0x$(printf "%x" "$WINDOWID")
-            if [[ $session_win_id == "$win_id" ]]; then
-                echo "$session_id"
-                return
-            fi
-        done
+    local window_id=$1
+
+    readarray -t session_ids < <(tmux list-sessions -F '#{session_id}')
+
+    for session_id in "${session_ids[@]}"; do
+        if [[ "$(tmux_window_id "$session_id")" == "$window_id" ]]; then
+            echo "$session_id"
+            return 0
+        fi
+    done
+
     return 1
 }
 
 tmux_active_pane_pid() {
-    local session_id=$1
+    local window_id=${1:?missing window id}
+    local session_id
+
+    session_id=$(tmux_session_id "$window_id")
+
     tmux list-panes -F '#{session_id} #{pane_active} #{pane_pid}' |
-        grep "^$session_id 1 " | head -n1 | awk '{print $NF}'
+        grep -m1 "^$session_id 1 " |
+        awk '{print $NF}' | tr -d '[:space:]'
 }
 
-unset copy_path_to_clipboard
-unset use_notifications
-unset OPTIND
 while getopts ":hwcn" option; do
     case $option in
-    w) win_id=$(selected-window) ;;
+    h) usage ;;
 
+    w) window_id=$(selected-window) ;;
     c) copy_path_to_clipboard=1 ;;
     n) use_notifications=1 ;;
 
-    h)
-        echo "$usage" >&2
-        exit 0
-        ;;
-    *)
-        echo "$usage" >&2
-        exit 1
-        ;;
+    *) die "invalid option '$option'" ;;
     esac
 done && shift $((OPTIND - 1))
 
-[[ -z $win_id ]] && win_id=$(active-window)
+[[ $window_id ]] || window_id=$1
+[[ $window_id ]] || window_id=$(active-window)
+[[ $window_id ]] || die "no window provided"
 
-if [[ -z $win_id ]]; then
-    message="no window found"
-    echo "$message" >&2
-    if [[ -n $use_notifications ]]; then
-        notify-send -u critical "$message"
-    fi
-    exit 1
-fi
+cwd=$HOME # fallback
 
-cwd=$PWD
-win_pid=$(xprop -id "$win_id" | grep -m1 PID | cut -f3 -d' ')
-if [[ -n $win_pid ]]; then
-    readarray -t procs < <(pstree -lpAT "$win_pid" | head -n1 | sed 's/-+-.*$//' | sed 's/---/\n/g' | tac)
+window_pid=$(
+    xprop -id "$window_id" | grep -m1 PID |
+        awk -F= '{print $2}' | tr -d '[:space:]'
+)
 
-    for proc in "${procs[@]}"; do
-        name=${proc%%(*}
-        pid=${proc//[^0-9]/}
+if [[ $window_pid ]]; then
+    readarray -t lines < <(
+        pstree --long --show-pids --ascii --hide-threads "$window_pid" |
+            head -n1 |
+            sed 's/-+-.*$//' |                           # ignore branches
+            sed 's/---/\n/g' |                           # one process per line
+            sed 's/^\(.*\)(\([[:digit:]]\+\))$/\1=\2/' | # separate name and pid
+            tac                                          # order processes by depth
+    )
 
+    for line in "${lines[@]}"; do
+        name=${line%%=*}
+        pid=${line##*=}
+
+        case $name in
         # If tmux is active in this window,
         # cwd will be whatever it was when tmux was started.
-        # There could be multiple panes, each with its own pid.
-        if [[ $name == tmux ]]; then
-            session_id=$(tmux_session_id "$win_id")
-            pid=$(tmux_active_pane_pid "$session_id")
+        # There could be multiple panes, each with its own pid and cwd.
+        tmux*) pid=$(tmux_active_pane_pid "$window_id") ;;
+
+        # Vim uses xclip to interact with the clipboard.
+        # It will be the innermost process, and encountered first.
+        # Its working directory is meaningless, so skip it.
+        xclip) continue ;;
+        esac
+
+        cwd_link=/proc/$pid/cwd
+        [[ -e $cwd_link ]] || continue
+
+        possible_cwd=$(readlink "$cwd_link")
+        if [[ -d $possible_cwd ]]; then
+            cwd=$possible_cwd
+            break
         fi
-
-        cwdlink=/proc/$pid/cwd
-
-        [[ -e $cwdlink ]] || continue
-
-        cwd=$(readlink "$cwdlink")
-
-        [[ -d $cwd ]] && break
     done
 fi
 
 if [[ -n $copy_path_to_clipboard ]]; then
-    echo "$cwd" | xsel -ib
+    xsel -ib <<<"$cwd"
     if [[ -n $use_notifications ]]; then
-        notify-send -i "$icon" "Working directory copied to clipboard:" "$cwd"
+        notify-send -i edit-copy "Working directory copied to clipboard:" "$cwd"
     fi
 fi
 
