Tinkering

diff --git a/files/home/.local/bin/bemenu-pass b/files/home/.local/bin/bemenu-pass
--- a/files/home/.local/bin/bemenu-pass
+++ b/files/home/.local/bin/bemenu-pass
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 
 set -euo pipefail
+shopt -s nullglob globstar
 
 password_length=16
 
-me=${0##*/}
 usage="Interact with pass using bemenu.
 
 Usage:
-    $me [OPTIONS] [ACTION]
+    ${0##*/} [OPTIONS] [ACTION]
 
 Options:
     -n NUMBER    generated password length
@@ -20,32 +20,22 @@ Actions:
     choose       choose existing password (default)
     generate     generate a new password
 
-In all cases, the password is copied to the clipboard.
-"
-
-pass_dir=${PASSWORD_STORE_DIR:-$HOME/.password-store}
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+In all cases, the password is copied to the clipboard."
 
 pass_names() {
-    if [[ ! -d $pass_dir ]]; then
-        return
+    local dir=${PASSWORD_STORE_DIR:-$HOME/.password-store}
+
+    if [[ ! -d $dir ]]; then
+        return 0
     fi
 
-    local file
-
-    find -L "$pass_dir" -type f -name "*.gpg" | while read -r file; do
-        local name=${file#"$pass_dir"/}
-        name=${name%.gpg}
-        printf "%s\n" "$name"
+    local path name
+    for path in "$dir"/**.gpg; do
+        if [[ -f $path ]]; then
+            name=${path#"$dir"/}
+            name=${name%.gpg}
+            printf "%s\n" "$name"
+        fi
     done
 }
 
@@ -55,8 +45,14 @@ while getopts ":n:qh" option; do
     case $option in
     n) password_length=$OPTARG ;;
     q) show_option=--qrcode ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -64,10 +60,16 @@ action=${1:-choose}
 
 case $action in
 choose | generate) ;;
-*) die "invalid action -- $action" ;;
+*)
+    printf "Invalid action: %s\n" "$action" >&2
+    exit 1
+    ;;
 esac
 
-name=$(pass_names | bemenu -b -p "$action password")
+if ! name=$(pass_names | bemenu -b -p "$action password") || [[ -z $name ]]; then
+    printf "No password name entered or selected\n" >&2
+    exit 1
+fi
 
 case $action in
 choose) pass show "$show_option" "$name" ;;
@@ -79,7 +81,7 @@ clipboard_seconds=${PASSWORD_STORE_CLIP_TIME:-45}
 if [[ $show_option == --clip ]]; then
     notify-send -i edit-copy-symbolic \
         -t $((clipboard_seconds * 1000)) \
-        -h string:x-canonical-private-synchronous:"$me" \
-        "Password for '$name' copied to clipboard" \
-        "Self-destructing in <b>$clipboard_seconds</b> seconds..." &
+        -h string:x-canonical-private-synchronous:"${0##*/}" \
+        "Copied $name to clipboard" \
+        "Will clear in <b>$clipboard_seconds</b> seconds..." &
 fi
diff --git a/files/home/.local/bin/bemenu-snip b/files/home/.local/bin/bemenu-snip
--- a/files/home/.local/bin/bemenu-snip
+++ b/files/home/.local/bin/bemenu-snip
@@ -2,39 +2,33 @@
 
 set -euo pipefail
 
-me=${0##*/}
 usage="Manage text snippets with bemenu.
 
 Usage:
-    $me [OPTIONS] ACTION NAME
+    ${0##*/} -h
+    ${0##*/} [OPTIONS] ACTION NAME
 
 Options:
-    -C DIRECTORY    directory in which to store snippets
+    -D DIRECTORY    directory in which to store snippets
 
 Actions:
-    edit            open snippet in editor
-    copy            copy snippet to clipboard
-    save            save clipboard to snippet
-    type            type snippet to active window
+    read            read snippet to clipboard
+    write           write clipboard to snippet
+    append          append clipboard to snippet
     delete          delete snippet
-"
+    edit            open snippet in editor
+    type            type snippet to active window"
 
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
-
-do_copy() {
+do_read() {
     snip "${snip_options[@]}" read "$1" | wl-copy
 }
 
-do_save() {
+do_write() {
     wl-paste | snip "${snip_options[@]}" write "$1"
+}
+
+do_append() {
+    wl-paste | snip "${snip_options[@]}" append "$1"
 }
 
 do_type() {
@@ -43,25 +37,43 @@ do_type() {
 
 snip_options=()
 
-while getopts ":C:h" option; do
+while getopts ":D:h" option; do
     case $option in
-    C) snip_options+=(-C "$OPTARG") ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    D) snip_options+=(-D "$OPTARG") ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
-action=${1:?missing action}
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be an action\n" >&2
+    exit 1
+fi
 
-name=$(snip list | bemenu -b -p "$action snippet")
+action=$1
 
-if [[ -z $name ]]; then
-    die "no snippet was selected"
+case $action in
+read | write | append | delete | edit | type) ;;
+*)
+    printf "Invalid action: %s\n" "$action" >&2
+    exit 1
+    ;;
+esac
+
+if ! name=$(snip list | bemenu -b -p "$action snippet" | head -n1) || [[ -z $name ]]; then
+    printf "No snippet name entered or selected\n" >&2
+    exit 1
 fi
 
 export EDITOR=${VISUAL:-gvim}
 
 case $action in
-edit | delete) snip "$action" "$name" ;;
+delete | edit) snip "${snip_options[@]}" "$action" "$name" ;;
 *) do_"$action" "$name" ;;
 esac
diff --git a/files/home/.local/bin/capture-image-camera b/files/home/.local/bin/capture-image-camera
--- a/files/home/.local/bin/capture-image-camera
+++ b/files/home/.local/bin/capture-image-camera
@@ -8,11 +8,10 @@ directory=$HOME
 file_name=camera_%FT%T%:z
 file_type=png
 
-me=${0##*/}
 usage="Capture an image from a video device.
 
 Usage:
-    $me [OPTIONS] [FILE]
+    ${0##*/} [OPTIONS] [FILE]
 
 Options:
     -e              edit the captured image before saving
@@ -32,20 +31,9 @@ Options:
 Arguments:
     FILE            output file (used instead of default)
                     formats any sequences recognized by strftime
-                    (default: $directory/$file_name.$file_type)
-"
+                    (default: $directory/$file_name.$file_type)"
 
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
-
-unset edit
+edit=0
 
 while getopts ":ed:D:N:E:h" option; do
     case $option in
@@ -54,16 +42,20 @@ while getopts ":ed:D:N:E:h" option; do
     D) directory=$OPTARG ;;
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
 output_file=$(date +"${1:-$directory/$file_name.$file_type}")
 
-capture_command=(
-    ffmpeg -hide_banner -y -f v4l2 -i "$device" -frames:v 1 -c:v "$file_type"
-)
+capture_command=(ffmpeg -hide_banner -y -f v4l2 -i "$device" -frames:v 1 -c:v "$file_type")
 
 # If a delay was requested, provide an audible countdown to let user know
 # something is about to happen.
@@ -73,7 +65,7 @@ fi
 
 mkdir -p "$(dirname "$output_file")"
 
-if [[ -v edit ]]; then
+if ((edit)); then
     # The editor is feedback that the capture has occurred.
     "${capture_command[@]}" -f image2 - | swappy -f - -o "$output_file"
 else
diff --git a/files/home/.local/bin/capture-image-desktop b/files/home/.local/bin/capture-image-desktop
--- a/files/home/.local/bin/capture-image-desktop
+++ b/files/home/.local/bin/capture-image-desktop
@@ -7,11 +7,10 @@ directory=$HOME
 file_name=desktop_%FT%T%:z
 file_type=png
 
-me=${0##*/}
 usage="Capture an image of the desktop.
 
 Usage:
-    $me [OPTIONS] [FILE]
+    ${0##*/} [OPTIONS] [FILE]
 
 Options:
     -g GEOMETRY     geometry of region to capture
@@ -39,48 +38,35 @@ Options:
 Arguments:
     FILE            output file (used instead of default)
                     formats any sequences recognized by strftime
-                    (default: $directory/$file_name.$file_type)
-"
+                    (default: $directory/$file_name.$file_type)"
 
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
+window_geometry() {
+    swaymsg -t get_tree | jq -r ".. | select(.rect? and .visible?${1:+ and .focused?}) | .rect | \"\(.x),\(.y) \(.width)x\(.height)\""
 }
 
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
-
-geometry_format='\(.x),\(.y) \(.width)x\(.height)'
-
-focused_window_geometry() {
-    swaymsg -t get_tree |
-        jq -r ".. | select(.rect? and .visible? and .focused?) | .rect | \"$geometry_format\""
-}
-
-select_window_geometry() {
-    swaymsg -t get_tree |
-        jq -r ".. | select(.rect? and .visible?) | .rect | \"$geometry_format\"" |
-        slurp -r
-}
-
-unset edit capture_mouse
+edit=0
+capture_mouse=0
 
 while getopts ":g:rfsmed:D:N:E:h" option; do
     case $option in
     g) geometry=$OPTARG ;;
     r) geometry=$(slurp) ;;
-    f) geometry=$(focused_window_geometry) ;;
-    s) geometry=$(select_window_geometry) ;;
+    f) geometry=$(window_geometry 1) ;;
+    s) geometry=$(window_geometry | slurp -r) ;;
     e) edit=1 ;;
     m) capture_mouse=1 ;;
     d) delay=$OPTARG ;;
     D) directory=$OPTARG ;;
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -92,7 +78,7 @@ if [[ -v geometry ]]; then
     capture_command+=(-g "$geometry")
 fi
 
-if [[ -v capture_mouse ]]; then
+if ((capture_mouse)); then
     capture_command+=(-c)
 fi
 
@@ -104,7 +90,7 @@ fi
 
 mkdir -p "$(dirname "$output_file")"
 
-if [[ -v edit ]]; then
+if ((edit)); then
     # The editor is feedback that the capture has occurred.
     "${capture_command[@]}" - | swappy -f - -o "$output_file"
 else
diff --git a/files/home/.local/bin/capture-pixel-desktop b/files/home/.local/bin/capture-pixel-desktop
--- a/files/home/.local/bin/capture-pixel-desktop
+++ b/files/home/.local/bin/capture-pixel-desktop
@@ -2,31 +2,25 @@
 
 set -euo pipefail
 
-me=${0##*/}
 usage="Capture the color value of a selected pixel to the clipboard.
 
 Usage:
-    $me TYPE
+    ${0##*/} TYPE
 
 Types:
     hex    output color as a hex string (ex: #rrggbb) (default)
-    rgb    output color as an RGB tuple (ex: (1,2,3))
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+    rgb    output color as an RGB tuple (ex: (1,2,3))"
 
 while getopts ":h" option; do
     case $option in
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -38,7 +32,7 @@ index=${indices[$name]}
 value=$(
     grim -g "$(slurp -p)" -t ppm - |
         convert - -format '%[pixel:p{0,0}]' txt:- |
-        tail -n1 | awk "{print \$$index}"
+        tail -n1 | awk -v i="$index" '{print $i}'
 )
 
 # Provide audible feedback that capture is complete.
diff --git a/files/home/.local/bin/capture-video-camera b/files/home/.local/bin/capture-video-camera
--- a/files/home/.local/bin/capture-video-camera
+++ b/files/home/.local/bin/capture-video-camera
@@ -8,11 +8,10 @@ directory=$HOME
 file_name=camera_%FT%T%:z
 file_type=mp4
 
-me=${0##*/}
 usage="Capture video from a camera device.
 
 Usage:
-    $me [OPTIONS] [FILE | 'stop']
+    ${0##*/} [OPTIONS] [FILE | 'stop']
     
 Options:
     -a              also capture audio from microphone
@@ -37,27 +36,10 @@ Options:
 Arguments:
     FILE            output file (used instead of default)
                     formats any sequences recognized by strftime
-                    (default: $directory/$file_name.$file_type)
-"
+                    (default: $directory/$file_name.$file_type)"
 
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
-
-stop_recording() {
-    if [[ -f $capture_command_stdin ]]; then
-        printf "q\n" >>"$capture_command_stdin"
-    fi
-    exit 0
-}
-
-capture_command_stdin=$XDG_RUNTIME_DIR/$me-command.stdin
+capture_audio=0
+capture_command_stdin=$XDG_RUNTIME_DIR/${0##*/}-command.stdin
 
 while getopts ":ai:d:D:N:E:Xh" option; do
     case $option in
@@ -67,9 +49,20 @@ while getopts ":ai:d:D:N:E:Xh" option; do
     D) directory=$OPTARG ;;
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
-    X) stop_recording ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    X)
+        if [[ -f $capture_command_stdin ]]; then
+            printf "q\n" >>"$capture_command_stdin"
+        fi
+        exit 0
+        ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -78,7 +71,7 @@ output_file=$(date +"${1:-$directory/$file_name.$file_type}")
 
 capture_command=(ffmpeg -hide_banner -y -f v4l2 -i "$device")
 
-if [[ -v capture_audio ]]; then
+if ((capture_audio)); then
     capture_command+=(-f alsa -i default)
 fi
 
@@ -110,7 +103,7 @@ else
 fi
 
 # If the capture file is a gif, optimize it.
-if [[ $output_file == *.gif ]]; then
+if [[ $output_file == *.gif ]] && command -v gifsicle >/dev/null; then
     gifsicle --batch --optimize=3 "$output_file"
 fi
 
diff --git a/files/home/.local/bin/capture-video-desktop b/files/home/.local/bin/capture-video-desktop
--- a/files/home/.local/bin/capture-video-desktop
+++ b/files/home/.local/bin/capture-video-desktop
@@ -7,11 +7,10 @@ directory=$HOME
 file_name=desktop_%FT%T%:z
 file_type=mp4
 
-me=${0##*/}
 usage="Capture video of the desktop.
 
 Usage:
-    $me [OPTIONS] [FILE]
+    ${0##*/} [OPTIONS] [FILE]
     
 Options:
     -g GEOMETRY     geometry of region to capture
@@ -39,55 +38,40 @@ Options:
 Arguments:
     FILE            output file (used instead of default)
                     formats any sequences recognized by strftime
-                    (default: $directory/$file_name.$file_type)
-"
+                    (default: $directory/$file_name.$file_type)"
 
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
+window_geometry() {
+    swaymsg -t get_tree | jq -r ".. | select(.rect? and .visible?${1:+ and .focused?}) | .rect | \"\(.x),\(.y) \(.width)x\(.height)\""
 }
 
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
-
-geometry_format='\(.x),\(.y) \(.width)x\(.height)'
-
-focused_window_geometry() {
-    swaymsg -t get_tree |
-        jq -r ".. | select(.rect? and .visible? and .focused?) | .rect | \"$geometry_format\""
-}
-
-select_window_geometry() {
-    swaymsg -t get_tree |
-        jq -r ".. | select(.rect? and .visible?) | .rect | \"$geometry_format\"" |
-        slurp -r
-}
-
-stop_recording() {
-    if [[ -f $capture_command_pid_file ]]; then
-        kill "$(<"$capture_command_pid_file")"
-    fi
-    exit 0
-}
-
-capture_command_pid_file=$XDG_RUNTIME_DIR/$me-command.pid
+capture_audio=0
+capture_command_pid_file=$XDG_RUNTIME_DIR/${0##*/}-command.pid
 
 while getopts ":g:rfsad:D:N:E:Xh" option; do
     case $option in
     g) geometry=$OPTARG ;;
     r) geometry=$(slurp) ;;
-    f) geometry=$(focused_window_geometry) ;;
-    s) geometry=$(select_window_geometry) ;;
+    f) geometry=$(window_geometry 1) ;;
+    s) geometry=$(window_geometry | slurp -r) ;;
     a) capture_audio=1 ;;
     d) delay=$OPTARG ;;
     D) directory=$OPTARG ;;
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
-    X) stop_recording ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    X)
+        if [[ -f $capture_command_pid_file ]]; then
+            kill "$(<"$capture_command_pid_file")"
+        fi
+        exit 0
+        ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -99,7 +83,7 @@ if [[ -v geometry ]]; then
     capture_command+=(-g "$geometry")
 fi
 
-if [[ -v capture_audio ]]; then
+if ((capture_audio)); then
     capture_command+=(-a)
 fi
 
@@ -130,7 +114,7 @@ else
 fi
 
 # If the capture file is a gif, optimize it.
-if [[ $output_file == *.gif ]]; then
+if [[ $output_file == *.gif ]] && command -v gifsicle >/dev/null; then
     gifsicle --batch --optimize=3 "$output_file"
 fi
 
diff --git a/files/home/.local/bin/qemu-system-pc-q35 b/files/home/.local/bin/qemu-system-pc-q35
--- a/files/home/.local/bin/qemu-system-pc-q35
+++ b/files/home/.local/bin/qemu-system-pc-q35
@@ -2,40 +2,46 @@
 
 set -euo pipefail
 
+usage="Execute a QEMU pc-q35 system with some common optimizations.
+
+Usage:
+    ${0##*/} [OPTIONS] [ARGUMENT...]
+
+Options:
+    -n NAME    specify the machine's process name
+    -m SIZE    specify machine's ram size (e.g. 4G)
+    -F RULE    add to the host forwarding rules (e.g. tcp::60022-:22)
+    -i FILE    add iso FILE as a cdrom"
+
 options=()
 hostfwds=()
-
-boot_from_iso=0
 
 cdrom_id=0
 cdrom_device_fmt="scsi-cd,bus=scsi0.0,drive=cdrom%d"
 cdrom_drive_fmt="id=cdrom%d,if=none,format=raw,media=cdrom,read-only=on,file=%s"
 
-while getopts "n:i:m:F:" option; do
+while getopts "n:m:F:i:h" option; do
     case $option in
-    n)
-        options+=(-name "$OPTARG")
-        ;;
+    n) options+=(-name "$OPTARG") ;;
+    m) options+=(-m "$OPTARG") ;;
+    F) hostfwds+=("$OPTARG") ;;
     i)
         id=$((cdrom_id++))
         options+=(
             -device "$(printf "$cdrom_device_fmt" "$id")"
             -drive "$(printf "$cdrom_drive_fmt" "$id" "$OPTARG")"
         )
-        boot_from_iso=1
         ;;
-    m)
-        options+=(-m "$OPTARG")
+    h)
+        printf "%s\n" "$usage"
+        exit 0
         ;;
-    F)
-        hostfwds+=("$OPTARG")
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
         ;;
     esac
 done && shift $((OPTIND - 1))
-
-if ((boot_from_iso)); then
-    options+=(-boot "order=d,menu=on")
-fi
 
 hostfwds_arg=$(paste -sd, <<<"${hostfwds[@]/#/hostfwd=}")
 
diff --git a/files/home/.local/bin/set-audio-volume b/files/home/.local/bin/set-audio-volume
--- a/files/home/.local/bin/set-audio-volume
+++ b/files/home/.local/bin/set-audio-volume
@@ -4,11 +4,10 @@ set -euo pipefail
 
 step=5
 
-me=${0##*/}
 usage="Set the audio volume and show a notification.
 
 Usage:
-    $me [OPTIONS] ACTION
+    ${0##*/} [OPTIONS] ACTION
 
 Options:
     -o           change volume for outputs (sinks)
@@ -27,18 +26,7 @@ Actions:
     down         decrease volume
     mute         toggle volume mute status
     max          set volume to maximum
-    NUMBER       set volume to NUMBER percent
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+    NUMBER       set volume to NUMBER percent"
 
 type_name=sink
 
@@ -48,8 +36,14 @@ while getopts ":ois:n:h" option; do
     o) type_name=sink ;;
     i) type_name=source ;;
     n) target_name=$OPTARG ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -60,7 +54,12 @@ if [[ ! -v target_name ]]; then
     esac
 fi
 
-action=${1:?missing action}
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be an action\n" >&2
+    exit 1
+fi
+
+action=$1
 
 case $action in
 mute) pactl set-"$type_name"-mute "$target_name" toggle ;;
@@ -68,6 +67,10 @@ up) pactl set-"$type_name"-volume "$target_name" +"$step%" ;;
 down) pactl set-"$type_name"-volume "$target_name" -"$step%" ;;
 max) pactl set-"$type_name"-volume "$target_name" 100% ;;
 [0-9]*) pactl set-"$type_name"-volume "$target_name" "$action" ;;
+*)
+    printf "Invalid action: %s\n" "$action" >&2
+    exit 1
+    ;;
 esac
 
 # If sway is running, refresh the status line to reflect the new volume.
@@ -76,9 +79,7 @@ if [[ -v SWAYSOCK ]]; then
     throttle swaystatus-refresh 1 killall -SIGUSR1 swaystatus &
 fi
 
-read -r left right < <(
-    pactl get-"$type_name"-volume "$target_name" | head -n1 | awk '{print $5,$12}'
-)
+read -r left right < <(pactl get-"$type_name"-volume "$target_name" | head -n1 | awk '{print $5,$12}')
 
 # If the left and right channel values are the same, just display one value.
 # Otherwise, show separate values for each channel.
@@ -89,7 +90,7 @@ else
 fi
 
 # Show a different icon depending on the mute status.
-if [[ $(pactl get-"$type_name"-mute "$target_name") == *yes ]]; then
+if [[ $(pactl get-"$type_name"-mute "$target_name" | awk '{print $NF}') == yes ]]; then
     case $type_name in
     sink) icon="audio-volume-muted-symbolic" ;;
     source) icon="microphone-disabled-symbolic" ;;
@@ -108,5 +109,5 @@ fi
 
 notify-send -u low -i "$icon" \
     -h int:value:"$volume" \
-    -h string:x-canonical-private-synchronous:"$me" \
+    -h string:x-canonical-private-synchronous:"${0##*/}" \
     "Volume Control" "Volume: $volume" &
diff --git a/files/home/.local/bin/set-display-brightness b/files/home/.local/bin/set-display-brightness
--- a/files/home/.local/bin/set-display-brightness
+++ b/files/home/.local/bin/set-display-brightness
@@ -2,38 +2,37 @@
 
 set -euo pipefail
 
-me=${0##*/}
 usage="Set the display brightness and show a notification.
 
 Usage:
-    $me ACTION
+    ${0##*/} ACTION
 
 Actions:
     up        increase brightness by one step
     down      decrease brightness by one step
     max       set brightness to maximum
     min       set brightness to minimum
-    NUMBER    set brightness to NUMBER
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+    NUMBER    set brightness to NUMBER"
 
 while getopts ":h" option; do
     case $option in
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
-action=${1:?missing action}
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be an action\n" >&2
+    exit 1
+fi
+
+action=$1
 
 case $action in
 up) brightnessctl set 1+ ;;
@@ -41,6 +40,10 @@ down) brightnessctl set 1- ;;
 max) brightnessctl set 100% ;;
 min) brightnessctl set 0% ;;
 [0-9]*) brightnessctl set "$action" ;;
+*)
+    printf "Invalid action: %s\n" "$action" >&2
+    exit 1
+    ;;
 esac
 
 value=$(brightnessctl get)
@@ -48,5 +51,5 @@ total=$(brightnessctl max)
 
 notify-send -u low -i display-brightness-symbolic \
     -h int:value:"$((value * 100 / total))" \
-    -h string:x-canonical-private-synchronous:"$me" \
+    -h string:x-canonical-private-synchronous:"${0##*/}" \
     "Brightness" "Level: $value" &
diff --git a/files/home/.local/bin/startw b/files/home/.local/bin/startw
--- a/files/home/.local/bin/startw
+++ b/files/home/.local/bin/startw
@@ -6,10 +6,12 @@ set -euo pipefail
 shopt -s nullglob
 
 for file in ~/.wprofile.d/*; do
-    [[ -f $file ]] || continue
-    . "$file" || printf "%s: line %s: unable to load file -- %s\n" "$0" "$LINENO" "$file" >&2
+    if [[ -f $file ]] && ! . "$file"; then
+        printf "Unable to source file: %q\n" "$file" >&2
+        exit 1
+    fi
 done
 unset file
 
-export XDG_CURRENT_DESKTOP=sway
-exec "$XDG_CURRENT_DESKTOP" 2>&1 | logger -t "$XDG_CURRENT_DESKTOP"
+export XDG_CURRENT_DESKTOP=$DESKTOP
+exec "$DESKTOP" 2>&1 | logger -t "$DESKTOP"
diff --git a/files/home/.local/bin/swaymark b/files/home/.local/bin/swaymark
--- a/files/home/.local/bin/swaymark
+++ b/files/home/.local/bin/swaymark
@@ -2,46 +2,51 @@
 
 set -euo pipefail
 
-me=${0##*/}
 usage="Interact with sway's container marks.
 
 Usage: 
-    $me ACTION
+    ${0##*/} ACTION
 
 Actions:
     set      set mark for current container
     unset    remove mark for current container
     clear    remove all container marks
-    goto     focus a marked container
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+    goto     focus a marked container"
 
 while getopts ":h" option; do
     case $option in
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
-action=${1:?missing action}
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be an action\n" >&2
+    exit 1
+fi
+
+action=$1
 
 case $action in
 set | goto) ;;
 unset) exec swaymsg '[con_id="__focused__"] unmark' ;;
 clear) exec swaymsg unmark ;;
-*) die "invalid action -- $action" ;;
+*)
+    printf "Invalid action: %s\n" "$action" >&2
+    exit 1
+    ;;
 esac
 
-mark=$(swaymsg -t get_marks | jq -r '.[]' | bemenu -p "$action mark")
+if ! mark=$(swaymsg -t get_marks | jq -r .[] | bemenu -p "$action mark") || [[ -z $mark ]]; then
+    printf "No mark entered or selected\n" >&2
+    exit 1
+fi
 
 case $action in
 set) exec swaymsg mark "$mark" ;;
diff --git a/files/home/.local/bin/swaymsg-input b/files/home/.local/bin/swaymsg-input
--- a/files/home/.local/bin/swaymsg-input
+++ b/files/home/.local/bin/swaymsg-input
@@ -4,11 +4,10 @@ set -euo pipefail
 
 prompt=input
 
-me=${0##*/}
 usage="Prompt the user for sway command input.
 
 Usage:
-    $me [OPTIONS] FORMAT
+    ${0##*/} [OPTIONS] FORMAT
 
 Options:
     -e         treat an empty response as an error
@@ -20,18 +19,7 @@ Options:
 
 Arguments:
     FORMAT     use FORMAT for sway command
-               (%s will be replaced by user input)
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+               (%s will be replaced by user input)"
 
 ipc_command=(swaymsg)
 treat_empty_as_error=0
@@ -41,22 +29,30 @@ while getopts ":p:es:h" option; do
     p) prompt=$OPTARG ;;
     e) treat_empty_as_error=1 ;;
     s) ipc_command+=(-s "$OPTARG") ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
-format=${1:?missing command format}
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be the command format\n" >&2
+    exit 1
+fi
 
-# Prompt user for input.
+format=$1
+
 reply=$(bemenu -p "$prompt" </dev/null)
 
 if ((treat_empty_as_error)) && [[ -z $reply ]]; then
     exit 1
 fi
 
-# Substitute user's reply into message format.
 printf -v message "$format" "$reply"
 
-# Send command to sway.
 exec "${ipc_command[@]}" "$message"
diff --git a/files/home/.local/bin/swaypwd b/files/home/.local/bin/swaypwd
--- a/files/home/.local/bin/swaypwd
+++ b/files/home/.local/bin/swaypwd
@@ -2,47 +2,40 @@
 
 set -euo pipefail
 
-me=${0##*/}
 usage="Print the working directory of a window.
 
 Usage:
-    $me [ID]
+    ${0##*/} [ID]
 
 Arguments:
     ID    print directory for window ID
-          (default: focused window)
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+          (default: focused window)"
 
 while getopts ":h" option; do
     case $option in
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
+jq_options=()
+
 if [[ -v 1 ]]; then
     # A window ID was given, so look at windows in every workspace.
-    window_pid=$(
-        swaymsg -t get_tree |
-            jq -r --argjson id "$1" '.. | select(.pid? and .id? and .id == $id) | .pid'
-    )
+    jq_filter='.. | select(.pid? and .id? and .id == $id) | .pid'
+    jq_options+=(--argjson id "$1")
 else
     # No window ID was given, so allow the user to select visible windows.
-    window_pid=$(
-        swaymsg -t get_tree |
-            jq -r '.. | select(.pid? and .visible? and .focused?) | .pid'
-    )
+    jq_filter='.. | select(.pid? and .visible? and .focused?) | .pid'
 fi
+
+window_pid=$(swaymsg -t get_tree | jq -r "${jq_options[@]}" "$jq_filter")
 
 # Fallback value, in case no window information or working directory is found.
 cwd=$HOME
@@ -63,7 +56,7 @@ if [[ -n $window_pid ]]; then
         pid=$next_pid
     done
 
-    cwd_link=/proc/"$pid"/cwd
+    cwd_link=/proc/$pid/cwd
 
     # The actual working directory is pointed to by the symlink.
     if possible_cwd=$(realpath "$cwd_link" 2>/dev/null); then
@@ -71,4 +64,4 @@ if [[ -n $window_pid ]]; then
     fi
 fi
 
-printf "%s\n" "$cwd"
+printf "%s" "$cwd"
diff --git a/files/home/.local/bin/timer b/files/home/.local/bin/timer
--- a/files/home/.local/bin/timer
+++ b/files/home/.local/bin/timer
@@ -2,47 +2,44 @@
 
 set -euo pipefail
 
-me=${0##*/}
 usage="Raise an alarm after a specified amount of time.
 
 Usage:
-    $me [OPTIONS] TIMESPEC
+    ${0##*/} [OPTIONS] TIMESPEC
 
 Options:
     -n NAME    descriptive name for timer
 
 Examples:
-    timer 1 minute
-    timer -n laundry 45 minutes
-    timer -n 'boat tour' 3 hours
-    timer -n 'very specific' now + 1 hour + 10 minutes
+    timer '1 minute'
+    timer -n laundry '45 minutes'
+    timer -n 'boat tour' '3 hours'
+    timer -n 'very specific' 'now + 1 hour + 10 minutes'
 
-See --date option in date(1) for the definition of TIMESPEC.
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+See --date option in date(1) for a complete definition of TIMESPEC."
 
 unset name
 
 while getopts ":n:h" option; do
     case $option in
     n) name=$OPTARG ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
-time_spec=${*:?missing time specification}
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be a time specification\n" >&2
+    exit 1
+fi
 
-at "$(date -d "$time_spec" +"%H:%M %Y-%m-%d")" <<-EOF
+at "$(date -d "$1" +"%H:%M %Y-%m-%d")" <<EOF
 export DISPLAY=$DISPLAY
 export WAYLAND_DISPLAY=$WAYLAND_DISPLAY
 canberra-gtk-play -i alarm-clock-elapsed &
diff --git a/files/home/.local/bin/udiskie-add-keyfile b/files/home/.local/bin/udiskie-add-keyfile
--- a/files/home/.local/bin/udiskie-add-keyfile
+++ b/files/home/.local/bin/udiskie-add-keyfile
@@ -6,11 +6,10 @@ config_dir=${XDG_CONFIG_HOME:-$HOME/.config}/udiskie
 keyfile_dir=${XDG_DATA_HOME:-$HOME/.local/share}/udiskie/keyfiles
 config_file=$config_dir/config.json
 
-me=${0##*/}
 usage="Remember an encrypted disk's keyfile for automatic mounting.
 
 Usage:
-    $me [OPTIONS] DEVICE KEYFILE
+    ${0##*/} [OPTIONS] DEVICE KEYFILE
 
 Options:
     -n NAME         use NAME for the keyfile instead of the UUID
@@ -22,18 +21,7 @@ Arguments:
     DEVICE          device to unlock with KEYFILE   
     KEYFILE         file capable of unlocking DEVICE
 
-It's expected that KEYFILE is already (or will be) added to DEVICE.
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+It's expected that KEYFILE is already (or will be) added to DEVICE."
 
 unset keyfile_name
 
@@ -41,18 +29,47 @@ while getopts ":n:C:h" option; do
     case $option in
     n) keyfile_name=$OPTARG ;;
     C) config_dir=$OPTARG ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
-device=${1:?missing device}
-keyfile_original=${2:?missing keyfile}
-
-# Lookup the uuid for the device.
-if ! uuid=$(sudo blkid -s UUID -o value "$device") || [[ -z $uuid ]]; then
-    die "unable to get UUID for device"
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be a device\n" >&2
+    exit 1
 fi
+
+if [[ ! -b $1 ]]; then
+    printf "File is not a device: %q\n" "$1" >&2
+    exit 1
+fi
+
+device=$1
+
+if [[ ! -v 2 ]]; then
+    printf "The second argument must be a keyfile\n" >&2
+    exit 1
+fi
+
+if [[ ! -f $2 ]]; then
+    printf "File does not exist: %q\n" "$2" >&2
+    exit 1
+fi
+
+keyfile_original=$2
+
+if ! uuid=$(sudo blkid -s UUID -o value "$device") || [[ -z $uuid ]]; then
+    printf "Unable to get UUID for device: %q\n" "$device" >&2
+    exit 1
+fi
+
+umask 077
 
 # If the config file doesn't exist, add a skeleton.
 if [[ ! -f $config_file ]]; then
@@ -60,33 +77,28 @@ if [[ ! -f $config_file ]]; then
     jq -n '.device_config=[]' >"$config_file"
 fi
 
-# Keep a copy of the keyfile for later.
+# Keep a copy of the keyfile for udiskie.
 mkdir -p "$keyfile_dir"
 keyfile_copy=$keyfile_dir/${keyfile_name:-$uuid}.bin
 sudo cp -v "$keyfile_original" "$keyfile_copy"
 sudo chown "$USER:$USER" "$keyfile_copy"
-sudo chmod 600 "$keyfile_copy"
 
 # Lookup the index for this uuid, if it already exists.
-index=$(
-    jq --arg uuid "$uuid" \
-        '.device_config | map(.id_uuid == $uuid) | index(true)' \
-        "$config_file"
-)
+index=$(jq --arg uuid "$uuid" '.device_config | map(.id_uuid == $uuid) | index(true)' "$config_file")
 
-options=(--arg keyfile "${keyfile_copy/$HOME/\~}")
+# Pass the keyfile to jq, but with the shortened home path (for portability).
+jq_options=(--arg keyfile "${keyfile_copy/$HOME/\~}")
 
 # Depending on whether or not the uuid exists, either add or update it.
 if [[ $index == null ]]; then
-    options+=(--arg uuid "$uuid")
-    query='.device_config += [{ "id_uuid": $uuid, "keyfile": $keyfile }]'
+    jq_options+=(--arg uuid "$uuid")
+    jq_filter='.device_config += [{ "id_uuid": $uuid, "keyfile": $keyfile }]'
 else
-    options+=(--arg index "$index")
-    query='.device_config[$index | tonumber].keyfile=$keyfile'
+    jq_options+=(--arg index "$index")
+    jq_filter='.device_config[$index | tonumber].keyfile=$keyfile'
 fi
 
-# Update the config file and (re)write it.
-jq "${options[@]}" "$query" "$config_file" | sponge "$config_file"
+jq "${jq_options[@]}" "$jq_filter" "$config_file" | sponge "$config_file"
 
 # Restart the service to pick up the config changes.
 systemctl --user restart udiskie.service
