make error messages more consistent

diff --git a/files/home/.local/bin/bemenu-pass b/files/home/.local/bin/bemenu-pass
--- a/files/home/.local/bin/bemenu-pass
+++ b/files/home/.local/bin/bemenu-pass
@@ -31,8 +31,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 pass_names() {
@@ -56,7 +56,7 @@ while getopts ":n:qh" option; do
     n) password_length=$OPTARG ;;
     q) show_option=--qrcode ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -64,7 +64,7 @@ action=${1:-choose}
 
 case $action in
 choose | generate) ;;
-*) die "invalid action '$action'" ;;
+*) die "invalid action -- $action" ;;
 esac
 
 name=$(pass_names | bemenu -b -p "$action password")
diff --git a/files/home/.local/bin/bemenu-snip b/files/home/.local/bin/bemenu-snip
--- a/files/home/.local/bin/bemenu-snip
+++ b/files/home/.local/bin/bemenu-snip
@@ -25,8 +25,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 do_copy() {
@@ -47,7 +47,7 @@ while getopts ":C:h" option; do
     case $option in
     C) snip_options+=(-C "$OPTARG") ;;
     h) usage ;;
-    *) die "invalid option: $OPTARG" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/capture-image-camera b/files/home/.local/bin/capture-image-camera
--- a/files/home/.local/bin/capture-image-camera
+++ b/files/home/.local/bin/capture-image-camera
@@ -41,8 +41,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 unset edit
@@ -55,7 +55,7 @@ while getopts ":ed:D:N:E:h" option; do
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/capture-pixel-desktop b/files/home/.local/bin/capture-pixel-desktop
--- a/files/home/.local/bin/capture-pixel-desktop
+++ b/files/home/.local/bin/capture-pixel-desktop
@@ -19,14 +19,14 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 while getopts ":h" option; do
     case $option in
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/capture-video-camera b/files/home/.local/bin/capture-video-camera
--- a/files/home/.local/bin/capture-video-camera
+++ b/files/home/.local/bin/capture-video-camera
@@ -46,8 +46,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 while getopts ":ai:d:D:N:E:h" option; do
@@ -59,7 +59,7 @@ while getopts ":ai:d:D:N:E:h" option; do
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/capture-video-desktop b/files/home/.local/bin/capture-video-desktop
--- a/files/home/.local/bin/capture-video-desktop
+++ b/files/home/.local/bin/capture-video-desktop
@@ -48,8 +48,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 geometry_format='\(.x),\(.y) \(.width)x\(.height)'
@@ -77,7 +77,7 @@ while getopts ":g:rfsad:D:N:E:h" option; do
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/disable-kernel-module b/files/home/.local/bin/disable-kernel-module
--- a/files/home/.local/bin/disable-kernel-module
+++ b/files/home/.local/bin/disable-kernel-module
@@ -18,21 +18,21 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 while getopts ":h" option; do
     case $option in
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
 # First, ensure all given module names are valid.
 for name in "${@:?missing module name(s)}"; do
     if ! modprobe --show --quiet "$name"; then
-        die "Invalid module '$name'"
+        die "invalid module -- $name"
     fi
 done
 
diff --git a/files/home/.local/bin/set-audio-volume b/files/home/.local/bin/set-audio-volume
--- a/files/home/.local/bin/set-audio-volume
+++ b/files/home/.local/bin/set-audio-volume
@@ -36,8 +36,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 type_name=sink
@@ -49,7 +49,7 @@ while getopts ":ois:n:h" option; do
     i) type_name=source ;;
     n) target_name=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/swaymark b/files/home/.local/bin/swaymark
--- a/files/home/.local/bin/swaymark
+++ b/files/home/.local/bin/swaymark
@@ -21,14 +21,14 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 while getopts ":h" option; do
     case $option in
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -38,7 +38,7 @@ case $action in
 set | goto) ;;
 unset) exec swaymsg '[con_id="__focused__"] unmark' ;;
 clear) exec swaymsg unmark ;;
-*) die "invalid action '$action'" ;;
+*) die "invalid action -- $action" ;;
 esac
 
 mark=$(swaymsg -t get_marks | jq -r '.[]' | bemenu -p "$action mark")
diff --git a/files/home/.local/bin/swaymsg-input b/files/home/.local/bin/swaymsg-input
--- a/files/home/.local/bin/swaymsg-input
+++ b/files/home/.local/bin/swaymsg-input
@@ -29,8 +29,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 ipc_command=(swaymsg)
@@ -42,7 +42,7 @@ while getopts ":p:es:h" option; do
     e) treat_empty_as_error=1 ;;
     s) ipc_command+=(-s "$OPTARG") ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/swaypwd b/files/home/.local/bin/swaypwd
--- a/files/home/.local/bin/swaypwd
+++ b/files/home/.local/bin/swaypwd
@@ -19,16 +19,16 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 while getopts ":h" option; do
     case $option in
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
-done && shift "$((OPTIND - 1))"
+done && shift $((OPTIND - 1))
 
 if [[ -v 1 ]]; then
     # A window ID was given, so look at windows in every workspace.
diff --git a/files/home/.local/bin/timer b/files/home/.local/bin/timer
--- a/files/home/.local/bin/timer
+++ b/files/home/.local/bin/timer
@@ -26,8 +26,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 unset name
@@ -36,15 +36,15 @@ while getopts ":n:h" option; do
     case $option in
     n) name=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
 time_spec=${*:?missing time specification}
 
 at "$(date -d "$time_spec" +"%H:%M %Y-%m-%d")" <<-EOF
-	export DISPLAY=$DISPLAY
-	export WAYLAND_DISPLAY=$WAYLAND_DISPLAY
-	canberra-gtk-play -i alarm-clock-elapsed &
-	notify-send -u critical -i dialog-information-symbolic "Timer elapsed" "${name:-}"
+export DISPLAY=$DISPLAY
+export WAYLAND_DISPLAY=$WAYLAND_DISPLAY
+canberra-gtk-play -i alarm-clock-elapsed &
+notify-send -u critical -i dialog-information-symbolic "Timer elapsed" "${name:-}"
 EOF
diff --git a/files/home/.local/bin/udiskie-add-keyfile b/files/home/.local/bin/udiskie-add-keyfile
--- a/files/home/.local/bin/udiskie-add-keyfile
+++ b/files/home/.local/bin/udiskie-add-keyfile
@@ -31,8 +31,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 unset keyfile_name
@@ -42,20 +42,12 @@ while getopts ":n:C:h" option; do
     n) keyfile_name=$OPTARG ;;
     C) config_dir=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
-if [[ ! -v 1 ]]; then
-    die "missing device"
-fi
-
-if [[ ! -v 2 ]]; then
-    die "missing keyfile"
-fi
-
-device=$1
-keyfile_original=$2
+device=${1:?missing device}
+keyfile_original=${2:?missing keyfile}
 
 # Lookup the uuid for the device.
 if ! uuid=$(sudo blkid -s UUID -o value "$device") || [[ -z $uuid ]]; then
