Tinkering

diff --git a/files/home/.local/bin/bemenu-pass b/files/home/.local/bin/bemenu-pass
--- a/files/home/.local/bin/bemenu-pass
+++ b/files/home/.local/bin/bemenu-pass
@@ -31,7 +31,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -56,7 +56,7 @@ while getopts ":n:qh" option; do
     n) password_length=$OPTARG ;;
     q) show_option=--qrcode ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -64,7 +64,7 @@ action=${1:-choose}
 
 case $action in
 choose | generate) ;;
-*) die "Invalid action '$action'" ;;
+*) die "invalid action '$action'" ;;
 esac
 
 name=$(pass_names | bemenu -b -p "$action password")
diff --git a/files/home/.local/bin/bemenu-snip b/files/home/.local/bin/bemenu-snip
--- a/files/home/.local/bin/bemenu-snip
+++ b/files/home/.local/bin/bemenu-snip
@@ -25,7 +25,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -47,20 +47,16 @@ while getopts ":C:h" option; do
     case $option in
     C) snip_options+=(-C "$OPTARG") ;;
     h) usage ;;
-    *) die "Invalid option: $OPTARG" ;;
+    *) die "invalid option: $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
-if [[ ! -v 1 ]]; then
-    die "Missing action"
-fi
-
-action=$1
+action=${1:?missing action}
 
 name=$(snip list | bemenu -b -p "$action snippet")
 
 if [[ -z $name ]]; then
-    die "No snippet was selected"
+    die "no snippet was selected"
 fi
 
 export EDITOR=${VISUAL:-gvim}
diff --git a/files/home/.local/bin/capture-image-camera b/files/home/.local/bin/capture-image-camera
--- a/files/home/.local/bin/capture-image-camera
+++ b/files/home/.local/bin/capture-image-camera
@@ -41,7 +41,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -55,7 +55,7 @@ while getopts ":ed:D:N:E:h" option; do
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/capture-image-desktop b/files/home/.local/bin/capture-image-desktop
--- a/files/home/.local/bin/capture-image-desktop
+++ b/files/home/.local/bin/capture-image-desktop
@@ -43,45 +43,45 @@ Arguments:
 "
 
 usage() {
-	printf "%s\n" "$usage"
-	exit 0
+    printf "%s\n" "$usage"
+    exit 0
 }
 
 die() {
-	printf "ERROR: %s\n" "$*" >&2
-	exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
+    exit 1
 }
 
 geometry_format='\(.x),\(.y) \(.width)x\(.height)'
 
 focused_window_geometry() {
-	swaymsg -t get_tree |
-		jq -r ".. | select(.rect? and .visible? and .focused?) | .rect | \"$geometry_format\""
+    swaymsg -t get_tree |
+        jq -r ".. | select(.rect? and .visible? and .focused?) | .rect | \"$geometry_format\""
 }
 
 select_window_geometry() {
-	swaymsg -t get_tree |
-		jq -r ".. | select(.rect? and .visible?) | .rect | \"$geometry_format\"" |
-		slurp -r
+    swaymsg -t get_tree |
+        jq -r ".. | select(.rect? and .visible?) | .rect | \"$geometry_format\"" |
+        slurp -r
 }
 
 unset edit capture_mouse
 
 while getopts ":g:rfsmed:D:N:E:h" option; do
-	case $option in
-	g) geometry=$OPTARG ;;
-	r) geometry=$(slurp) ;;
-	f) geometry=$(focused_window_geometry) ;;
-	s) geometry=$(select_window_geometry) ;;
-	e) edit=1 ;;
-	m) capture_mouse=1 ;;
-	d) delay=$OPTARG ;;
-	D) directory=$OPTARG ;;
-	N) file_name=$OPTARG ;;
-	E) file_type=$OPTARG ;;
-	h) usage ;;
-	*) die "Invalid option '$OPTARG'" ;;
-	esac
+    case $option in
+    g) geometry=$OPTARG ;;
+    r) geometry=$(slurp) ;;
+    f) geometry=$(focused_window_geometry) ;;
+    s) geometry=$(select_window_geometry) ;;
+    e) edit=1 ;;
+    m) capture_mouse=1 ;;
+    d) delay=$OPTARG ;;
+    D) directory=$OPTARG ;;
+    N) file_name=$OPTARG ;;
+    E) file_type=$OPTARG ;;
+    h) usage ;;
+    *) die "invalid option '$OPTARG'" ;;
+    esac
 done && shift $((OPTIND - 1))
 
 output_file=$(date +"${1:-$directory/$file_name.$file_type}")
@@ -89,28 +89,28 @@ output_file=$(date +"${1:-$directory/$file_name.$file_type}")
 capture_command=(grim)
 
 if [[ -v geometry ]]; then
-	capture_command+=(-g "$geometry")
+    capture_command+=(-g "$geometry")
 fi
 
 if [[ -v capture_mouse ]]; then
-	capture_command+=(-c)
+    capture_command+=(-c)
 fi
 
 # If a delay was requested, provide an audible countdown to let user know
 # something is about to happen.
 if ((delay > 0)); then
-	canberra-gtk-play -l "$delay" -i message
+    canberra-gtk-play -l "$delay" -i message
 fi
 
 mkdir -p "$(dirname "$output_file")"
 
 if [[ -v edit ]]; then
-	# The editor is feedback that the capture has occurred.
-	"${capture_command[@]}" - | swappy -f - -o "$output_file"
+    # The editor is feedback that the capture has occurred.
+    "${capture_command[@]}" - | swappy -f - -o "$output_file"
 else
-	"${capture_command[@]}" "$output_file"
-	# Provide audible feedback that capture is complete.
-	canberra-gtk-play -i screen-capture &
+    "${capture_command[@]}" "$output_file"
+    # Provide audible feedback that capture is complete.
+    canberra-gtk-play -i screen-capture &
 fi
 
 wl-copy -n "$output_file"
diff --git a/files/home/.local/bin/capture-video-camera b/files/home/.local/bin/capture-video-camera
--- a/files/home/.local/bin/capture-video-camera
+++ b/files/home/.local/bin/capture-video-camera
@@ -46,7 +46,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -59,7 +59,7 @@ while getopts ":ai:d:D:N:E:h" option; do
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/capture-video-desktop b/files/home/.local/bin/capture-video-desktop
--- a/files/home/.local/bin/capture-video-desktop
+++ b/files/home/.local/bin/capture-video-desktop
@@ -48,7 +48,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -77,7 +77,7 @@ while getopts ":g:rfsad:D:N:E:h" option; do
     N) file_name=$OPTARG ;;
     E) file_type=$OPTARG ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/disable-kernel-module b/files/home/.local/bin/disable-kernel-module
--- a/files/home/.local/bin/disable-kernel-module
+++ b/files/home/.local/bin/disable-kernel-module
@@ -18,23 +18,19 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
 while getopts ":h" option; do
     case $option in
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
-if (($# == 0)); then
-    die "Missing module name(s)"
-fi
-
 # First, ensure all given module names are valid.
-for name in "$@"; do
+for name in "${@:?missing module name(s)}"; do
     if ! modprobe --show --quiet "$name"; then
         die "Invalid module '$name'"
     fi
diff --git a/files/home/.local/bin/set-audio-volume b/files/home/.local/bin/set-audio-volume
--- a/files/home/.local/bin/set-audio-volume
+++ b/files/home/.local/bin/set-audio-volume
@@ -36,7 +36,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -49,7 +49,7 @@ while getopts ":ois:n:h" option; do
     i) type_name=source ;;
     n) target_name=$OPTARG ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -60,11 +60,7 @@ if [[ ! -v target_name ]]; then
     esac
 fi
 
-if [[ ! -v 1 ]]; then
-    die "Missing action"
-fi
-
-action=$1
+action=${1:?missing action}
 
 case $action in
 mute) pactl set-"$type_name"-mute "$target_name" toggle ;;
diff --git a/files/home/.local/bin/set-display-brightness b/files/home/.local/bin/set-display-brightness
--- a/files/home/.local/bin/set-display-brightness
+++ b/files/home/.local/bin/set-display-brightness
@@ -22,22 +22,18 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
 while getopts ":h" option; do
     case $option in
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
-if [[ ! -v 1 ]]; then
-    die "Missing action"
-fi
-
-action=$1
+action=${1:?missing action}
 
 case $action in
 up) brightnessctl set 1+ ;;
diff --git a/files/home/.local/bin/swaymsg-input b/files/home/.local/bin/swaymsg-input
--- a/files/home/.local/bin/swaymsg-input
+++ b/files/home/.local/bin/swaymsg-input
@@ -29,7 +29,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -42,15 +42,11 @@ while getopts ":p:es:h" option; do
     e) treat_empty_as_error=1 ;;
     s) ipc_command+=(-s "$OPTARG") ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
-if [[ ! -v 1 ]]; then
-    die "Missing command format"
-fi
-
-format=$1
+format=${1:?missing command format}
 
 # Prompt user for input.
 reply=$(bemenu -p "$prompt" </dev/null)
diff --git a/files/home/.local/bin/timer b/files/home/.local/bin/timer
--- a/files/home/.local/bin/timer
+++ b/files/home/.local/bin/timer
@@ -26,7 +26,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -36,15 +36,14 @@ while getopts ":n:h" option; do
     case $option in
     n) name=$OPTARG ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
-if (($# == 0)); then
-    die "Missing time specification"
-fi
+time_spec=${*:?missing time specification}
 
-at "$(date -d "$*" +"%H:%M %Y-%m-%d")" <<-EOF
+at "$(date -d "$time_spec" +"%H:%M %Y-%m-%d")" <<-EOF
+	export DISPLAY=$DISPLAY
 	export WAYLAND_DISPLAY=$WAYLAND_DISPLAY
 	canberra-gtk-play -i alarm-clock-elapsed &
 	notify-send -u critical -i dialog-information-symbolic "Timer elapsed" "${name:-}"
diff --git a/files/home/.local/bin/udiskie-add-keyfile b/files/home/.local/bin/udiskie-add-keyfile
--- a/files/home/.local/bin/udiskie-add-keyfile
+++ b/files/home/.local/bin/udiskie-add-keyfile
@@ -31,7 +31,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -42,16 +42,16 @@ while getopts ":n:C:h" option; do
     n) keyfile_name=$OPTARG ;;
     C) config_dir=$OPTARG ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
 if [[ ! -v 1 ]]; then
-    die "Missing device"
+    die "missing device"
 fi
 
 if [[ ! -v 2 ]]; then
-    die "Missing keyfile"
+    die "missing keyfile"
 fi
 
 device=$1
@@ -59,7 +59,7 @@ keyfile_original=$2
 
 # Lookup the uuid for the device.
 if ! uuid=$(sudo blkid -s UUID -o value "$device") || [[ -z $uuid ]]; then
-    die "Unable to get UUID for device"
+    die "unable to get UUID for device"
 fi
 
 # If the config file doesn't exist, add a skeleton.
