config changes

diff --git a/stow/dotfiles/.local/bin/enable-lightdm-autologin b/stow/dotfiles/.local/bin/enable-lightdm-autologin
--- a/stow/dotfiles/.local/bin/enable-lightdm-autologin
+++ b/stow/dotfiles/.local/bin/enable-lightdm-autologin
@@ -9,13 +9,13 @@ user=${1:-$USER}
 config=/etc/lightdm/lightdm.conf
 
 if ! test -f "$config"; then
-    echo "Missing config file $config" >&2
-    exit 1
+	echo "Missing config file $config" >&2
+	exit 1
 fi
 
 # usage: enable_line filename name [value]
 enable_line() {
-    sudo sed -i "/^#\?$1=/{ s/^#//; ${2:+s/=.*/=$2/;} }" "$config"
+	sudo sed -i "/^#\?$1=/{ s/^#//; ${2:+s/=.*/=$2/;} }" "$config"
 }
 
 sudo groupadd -r autologin || true
diff --git a/stow/dotfiles/.local/bin/get-minecraft-forge b/stow/dotfiles/.local/bin/get-minecraft-forge
--- a/stow/dotfiles/.local/bin/get-minecraft-forge
+++ b/stow/dotfiles/.local/bin/get-minecraft-forge
@@ -6,8 +6,8 @@
 set -e
 
 die() {
-    echo "$@" >&2
-    exit 1
+	echo "$@" >&2
+	exit 1
 }
 
 me=${0##*/}
@@ -25,24 +25,24 @@ indexurl=$url/maven/net/minecraftforge/forge/index_$version.html
 curl -sL -o "$index" "$indexurl" || die "Could not get index page"
 
 build=$(
-    grep latest "$index" |
-    grep '^ *[0-9]' |
-    sed -e 's/^ *//' -e 's/<.*//'
+	grep latest "$index" |
+	grep '^ *[0-9]' |
+	sed -e 's/^ *//' -e 's/<.*//'
 )
 
 test "$build" || die "Unable to get the latest forge version for $version"
 
 path=$(
-    grep "Direct Download" "$index" |
-    grep "forge-$version-$build-$package" |
-    head -n1 | sed 's/.*href="\([^"]\+\)".*/\1/'
+	grep "Direct Download" "$index" |
+	grep "forge-$version-$build-$package" |
+	head -n1 | sed 's/.*href="\([^"]\+\)".*/\1/'
 )
 file=${path##*/}
 
 test "$file" || die "Could not parse filename"
 
 if ! test -f "$file"; then
-    curl -sL -o "$file" "$url/$path" || die "Could not download package"
+	curl -sL -o "$file" "$url/$path" || die "Could not download package"
 fi
 
 echo "$file"
diff --git a/stow/dotfiles/.local/bin/install-krita b/stow/dotfiles/.local/bin/install-krita
--- a/stow/dotfiles/.local/bin/install-krita
+++ b/stow/dotfiles/.local/bin/install-krita
@@ -8,13 +8,13 @@ index=https://krita.org/en/download/krita-desktop/
 
 url=$(
 	curl -sL "$index" |
-    grep -E 'https://[^"]+\.appimage' |
-    sed 's/.*"\(.*\)".*/\1/'
+	grep -E 'https://[^"]+\.appimage' |
+	sed 's/.*"\(.*\)".*/\1/'
 )
 
-if ! test "$url"; then
-    echo "Unable to get download url from $index" >&2
-    exit 1
+if [[ ! $url ]]; then
+	echo "Unable to get download url from $index" >&2
+	exit 1
 fi
 
 bin=$HOME/.local/bin/krita
diff --git a/stow/dotfiles/.local/bin/install-minecraft-client-forge b/stow/dotfiles/.local/bin/install-minecraft-client-forge
--- a/stow/dotfiles/.local/bin/install-minecraft-client-forge
+++ b/stow/dotfiles/.local/bin/install-minecraft-client-forge
@@ -13,13 +13,13 @@ mkdir -p "$dir"; cd "$dir"
 
 build=$(get-minecraft-forge "$version" installer)
 
-if ! test -f "$build"; then
-    echo "Unable to download installer for $version" >&2
-    exit 1
+if [[ ! -f $build ]]; then
+	echo "Unable to download installer for $version" >&2
+	exit 1
 fi
 
 installer=forge-$version-installer.jar
-test -f "$installer" || ln -sfv "$build" "$installer"
+[[ -f $installer ]] || ln -sfv "$build" "$installer"
 
 echo "Be sure to install to $dir!" >&2
 
diff --git a/stow/dotfiles/.local/bin/install-minecraft-server-forge b/stow/dotfiles/.local/bin/install-minecraft-server-forge
--- a/stow/dotfiles/.local/bin/install-minecraft-server-forge
+++ b/stow/dotfiles/.local/bin/install-minecraft-server-forge
@@ -13,17 +13,17 @@ mkdir -p "$dir"; cd "$dir"
 installer=forge-$version-installer.jar
 build=$(get-minecraft-forge "$version" installer)
 
-test -f "$installer" || ln -sfv "$build" "$installer"
+[[ -f $installer ]] || ln -sfv "$build" "$installer"
 
-if ! test -f "$installer"; then
-    echo "Unable to download installer for $version" >&2
-    exit 1
+if [[ ! -f $installer ]]; then
+	echo "Unable to download installer for $version" >&2
+	exit 1
 fi
 
 universal=${build/installer/universal}
 forge=forge-$version.jar
 
-test -f "$universal" || java -jar "$installer" --installServer
+[[ -f $universal ]] || java -jar "$installer" --installServer
 
 ln -sfv "$universal" "$forge"
 ln -sfv "$forge" forge.jar
diff --git a/stow/dotfiles/.local/bin/mon b/stow/dotfiles/.local/bin/mon
--- a/stow/dotfiles/.local/bin/mon
+++ b/stow/dotfiles/.local/bin/mon
@@ -7,81 +7,81 @@ Usage: $me [-h] [-f [command]
 "
 
 pid_status() {
-    local pid=$1
-    local status=$(ps -p "$pid" -o stat= 2>/dev/null) || return 1
-    case $status in
-        D*) desc="blocking" ;;
-        R*) desc="running" ;;
-        S*) desc="waiting" ;;
-        T*) desc="stopped" ;;
-        W*) desc="paging" ;;
-        X*) desc="dead" ;;
-        Z*) desc="a zombie" ;;
-        *) return 1 ;;
-    esac
-    echo "$desc"
+	local pid=$1
+	local status=$(ps -p "$pid" -o stat= 2>/dev/null) || return 1
+	case $status in
+		D*) desc="blocking" ;;
+		R*) desc="running" ;;
+		S*) desc="waiting" ;;
+		T*) desc="stopped" ;;
+		W*) desc="paging" ;;
+		X*) desc="dead" ;;
+		Z*) desc="a zombie" ;;
+		*) return 1 ;;
+	esac
+	echo "$desc"
 }
 
 pid_time() {
-    local pid=$1
-    local seconds=$(ps -p "$pid" -o etimes= 2>/dev/null)
-    secspan "$seconds"
+	local pid=$1
+	local seconds=$(ps -p "$pid" -o etimes= 2>/dev/null)
+	secspan "$seconds"
 }
 
 seconds=1
 monfile=/dev/null
 unset OPTIND
 while getopts ":hf:s:n" option; do
-    case $option in
-        f) monfile=$OPTARG ;;
-        s) seconds=$OPTARG ;;
-        n) notify=1 ;;
+	case $option in
+		f) monfile=$OPTARG ;;
+		s) seconds=$OPTARG ;;
+		n) notify=1 ;;
 
-        h) echo "$usage" >&2; exit 0 ;;
-        *) echo "$usage" >&2; exit 1 ;;
-    esac
+		h) echo "$usage" >&2; exit 0 ;;
+		*) echo "$usage" >&2; exit 1 ;;
+	esac
 done && shift $((OPTIND - 1))
 
 {
-    # start the command
-    date +"%c"
-    echo "$ $*"
-    "$@" 2>&1 &
-    pid=$!
+	# start the command
+	date +"%c"
+	echo "$ $*"
+	"$@" 2>&1 &
+	pid=$!
 
-    # if $0 dies, cleanup the process being monitored
-    trap "kill -9 $pid" INT TERM EXIT
+	# if $0 dies, cleanup the process being monitored
+	trap "kill -9 $pid" INT TERM EXIT
 
-    old_status="started"
-    message="process $pid is $old_status"
-    echo "# $message"
-    [[ $notify ]] && notify-send -u low "$message" "$*"
+	old_status="started"
+	message="process $pid is $old_status"
+	echo "# $message"
+	[[ $notify ]] && notify-send -u low "$message" "$*"
 
-    while true; do
-        new_status=$(pid_status $pid) || break
-        if [[ -n $new_status && $new_status != "$old_status" ]]; then
-            message="process $pid is $new_status (was $old_status)"
-            time=$(pid_time $pid)
-            [[ $time ]] && message+=", running for $time"
-            echo "# $message"
-            notify-send -u low "$message" "$*"
-        fi
-        sleep "$seconds"
-    done
+	while true; do
+		new_status=$(pid_status $pid) || break
+		if [[ -n $new_status && $new_status != "$old_status" ]]; then
+			message="process $pid is $new_status (was $old_status)"
+			time=$(pid_time $pid)
+			[[ $time ]] && message+=", running for $time"
+			echo "# $message"
+			notify-send -u low "$message" "$*"
+		fi
+		sleep "$seconds"
+	done
 
-    wait $pid; e=$?
+	wait $pid; e=$?
 
-    # post-mortem report
-    if (( e == 0 )); then
-        urgency="normal"
-        summary="succeeded"
-    else
-        urgency="critical"
-        summary="failed ($e)"
-    fi
+	# post-mortem report
+	if (( e == 0 )); then
+		urgency="normal"
+		summary="succeeded"
+	else
+		urgency="critical"
+		summary="failed ($e)"
+	fi
 
-    message="process $pid $summary"
-    notify-send -u $urgency "$message" "$*"
-    echo "# $message"
+	message="process $pid $summary"
+	notify-send -u $urgency "$message" "$*"
+	echo "# $message"
 
 } | tee "$monfile"
